// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdjustTrackingInfo.proto

package raidengame.cache.protobuf;

public final class AdjustTrackingInfoOuterClass {
  private AdjustTrackingInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdjustTrackingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdjustTrackingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string JFAMBDKKDHE = 2;</code>
     * @return The jFAMBDKKDHE.
     */
    java.lang.String getJFAMBDKKDHE();
    /**
     * <code>string JFAMBDKKDHE = 2;</code>
     * @return The bytes for jFAMBDKKDHE.
     */
    com.google.protobuf.ByteString
        getJFAMBDKKDHEBytes();

    /**
     * <code>string JLKFDDDPPHD = 3;</code>
     * @return The jLKFDDDPPHD.
     */
    java.lang.String getJLKFDDDPPHD();
    /**
     * <code>string JLKFDDDPPHD = 3;</code>
     * @return The bytes for jLKFDDDPPHD.
     */
    com.google.protobuf.ByteString
        getJLKFDDDPPHDBytes();

    /**
     * <code>string MGDJMEMFBCD = 8;</code>
     * @return The mGDJMEMFBCD.
     */
    java.lang.String getMGDJMEMFBCD();
    /**
     * <code>string MGDJMEMFBCD = 8;</code>
     * @return The bytes for mGDJMEMFBCD.
     */
    com.google.protobuf.ByteString
        getMGDJMEMFBCDBytes();

    /**
     * <code>string BDOFCOCOCPH = 11;</code>
     * @return The bDOFCOCOCPH.
     */
    java.lang.String getBDOFCOCOCPH();
    /**
     * <code>string BDOFCOCOCPH = 11;</code>
     * @return The bytes for bDOFCOCOCPH.
     */
    com.google.protobuf.ByteString
        getBDOFCOCOCPHBytes();

    /**
     * <code>string LGMPOGACDHA = 13;</code>
     * @return The lGMPOGACDHA.
     */
    java.lang.String getLGMPOGACDHA();
    /**
     * <code>string LGMPOGACDHA = 13;</code>
     * @return The bytes for lGMPOGACDHA.
     */
    com.google.protobuf.ByteString
        getLGMPOGACDHABytes();

    /**
     * <code>string KIBFINHDCKO = 15;</code>
     * @return The kIBFINHDCKO.
     */
    java.lang.String getKIBFINHDCKO();
    /**
     * <code>string KIBFINHDCKO = 15;</code>
     * @return The bytes for kIBFINHDCKO.
     */
    com.google.protobuf.ByteString
        getKIBFINHDCKOBytes();
  }
  /**
   * Protobuf type {@code AdjustTrackingInfo}
   */
  public static final class AdjustTrackingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdjustTrackingInfo)
      AdjustTrackingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustTrackingInfo.newBuilder() to construct.
    private AdjustTrackingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustTrackingInfo() {
      jFAMBDKKDHE_ = "";
      jLKFDDDPPHD_ = "";
      mGDJMEMFBCD_ = "";
      bDOFCOCOCPH_ = "";
      lGMPOGACDHA_ = "";
      kIBFINHDCKO_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdjustTrackingInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustTrackingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              jFAMBDKKDHE_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              jLKFDDDPPHD_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              mGDJMEMFBCD_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              bDOFCOCOCPH_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              lGMPOGACDHA_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              kIBFINHDCKO_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.internal_static_AdjustTrackingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.internal_static_AdjustTrackingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.class, raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.Builder.class);
    }

    public static final int JFAMBDKKDHE_FIELD_NUMBER = 2;
    private volatile java.lang.Object jFAMBDKKDHE_;
    /**
     * <code>string JFAMBDKKDHE = 2;</code>
     * @return The jFAMBDKKDHE.
     */
    @java.lang.Override
    public java.lang.String getJFAMBDKKDHE() {
      java.lang.Object ref = jFAMBDKKDHE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jFAMBDKKDHE_ = s;
        return s;
      }
    }
    /**
     * <code>string JFAMBDKKDHE = 2;</code>
     * @return The bytes for jFAMBDKKDHE.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJFAMBDKKDHEBytes() {
      java.lang.Object ref = jFAMBDKKDHE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jFAMBDKKDHE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JLKFDDDPPHD_FIELD_NUMBER = 3;
    private volatile java.lang.Object jLKFDDDPPHD_;
    /**
     * <code>string JLKFDDDPPHD = 3;</code>
     * @return The jLKFDDDPPHD.
     */
    @java.lang.Override
    public java.lang.String getJLKFDDDPPHD() {
      java.lang.Object ref = jLKFDDDPPHD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jLKFDDDPPHD_ = s;
        return s;
      }
    }
    /**
     * <code>string JLKFDDDPPHD = 3;</code>
     * @return The bytes for jLKFDDDPPHD.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJLKFDDDPPHDBytes() {
      java.lang.Object ref = jLKFDDDPPHD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jLKFDDDPPHD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MGDJMEMFBCD_FIELD_NUMBER = 8;
    private volatile java.lang.Object mGDJMEMFBCD_;
    /**
     * <code>string MGDJMEMFBCD = 8;</code>
     * @return The mGDJMEMFBCD.
     */
    @java.lang.Override
    public java.lang.String getMGDJMEMFBCD() {
      java.lang.Object ref = mGDJMEMFBCD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mGDJMEMFBCD_ = s;
        return s;
      }
    }
    /**
     * <code>string MGDJMEMFBCD = 8;</code>
     * @return The bytes for mGDJMEMFBCD.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMGDJMEMFBCDBytes() {
      java.lang.Object ref = mGDJMEMFBCD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mGDJMEMFBCD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BDOFCOCOCPH_FIELD_NUMBER = 11;
    private volatile java.lang.Object bDOFCOCOCPH_;
    /**
     * <code>string BDOFCOCOCPH = 11;</code>
     * @return The bDOFCOCOCPH.
     */
    @java.lang.Override
    public java.lang.String getBDOFCOCOCPH() {
      java.lang.Object ref = bDOFCOCOCPH_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bDOFCOCOCPH_ = s;
        return s;
      }
    }
    /**
     * <code>string BDOFCOCOCPH = 11;</code>
     * @return The bytes for bDOFCOCOCPH.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBDOFCOCOCPHBytes() {
      java.lang.Object ref = bDOFCOCOCPH_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bDOFCOCOCPH_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LGMPOGACDHA_FIELD_NUMBER = 13;
    private volatile java.lang.Object lGMPOGACDHA_;
    /**
     * <code>string LGMPOGACDHA = 13;</code>
     * @return The lGMPOGACDHA.
     */
    @java.lang.Override
    public java.lang.String getLGMPOGACDHA() {
      java.lang.Object ref = lGMPOGACDHA_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lGMPOGACDHA_ = s;
        return s;
      }
    }
    /**
     * <code>string LGMPOGACDHA = 13;</code>
     * @return The bytes for lGMPOGACDHA.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLGMPOGACDHABytes() {
      java.lang.Object ref = lGMPOGACDHA_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lGMPOGACDHA_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIBFINHDCKO_FIELD_NUMBER = 15;
    private volatile java.lang.Object kIBFINHDCKO_;
    /**
     * <code>string KIBFINHDCKO = 15;</code>
     * @return The kIBFINHDCKO.
     */
    @java.lang.Override
    public java.lang.String getKIBFINHDCKO() {
      java.lang.Object ref = kIBFINHDCKO_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kIBFINHDCKO_ = s;
        return s;
      }
    }
    /**
     * <code>string KIBFINHDCKO = 15;</code>
     * @return The bytes for kIBFINHDCKO.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKIBFINHDCKOBytes() {
      java.lang.Object ref = kIBFINHDCKO_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kIBFINHDCKO_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jFAMBDKKDHE_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jFAMBDKKDHE_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jLKFDDDPPHD_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jLKFDDDPPHD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mGDJMEMFBCD_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mGDJMEMFBCD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bDOFCOCOCPH_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, bDOFCOCOCPH_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lGMPOGACDHA_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, lGMPOGACDHA_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kIBFINHDCKO_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, kIBFINHDCKO_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jFAMBDKKDHE_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jFAMBDKKDHE_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jLKFDDDPPHD_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jLKFDDDPPHD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mGDJMEMFBCD_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, mGDJMEMFBCD_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bDOFCOCOCPH_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, bDOFCOCOCPH_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lGMPOGACDHA_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, lGMPOGACDHA_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kIBFINHDCKO_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, kIBFINHDCKO_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo other = (raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo) obj;

      if (!getJFAMBDKKDHE()
          .equals(other.getJFAMBDKKDHE())) return false;
      if (!getJLKFDDDPPHD()
          .equals(other.getJLKFDDDPPHD())) return false;
      if (!getMGDJMEMFBCD()
          .equals(other.getMGDJMEMFBCD())) return false;
      if (!getBDOFCOCOCPH()
          .equals(other.getBDOFCOCOCPH())) return false;
      if (!getLGMPOGACDHA()
          .equals(other.getLGMPOGACDHA())) return false;
      if (!getKIBFINHDCKO()
          .equals(other.getKIBFINHDCKO())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JFAMBDKKDHE_FIELD_NUMBER;
      hash = (53 * hash) + getJFAMBDKKDHE().hashCode();
      hash = (37 * hash) + JLKFDDDPPHD_FIELD_NUMBER;
      hash = (53 * hash) + getJLKFDDDPPHD().hashCode();
      hash = (37 * hash) + MGDJMEMFBCD_FIELD_NUMBER;
      hash = (53 * hash) + getMGDJMEMFBCD().hashCode();
      hash = (37 * hash) + BDOFCOCOCPH_FIELD_NUMBER;
      hash = (53 * hash) + getBDOFCOCOCPH().hashCode();
      hash = (37 * hash) + LGMPOGACDHA_FIELD_NUMBER;
      hash = (53 * hash) + getLGMPOGACDHA().hashCode();
      hash = (37 * hash) + KIBFINHDCKO_FIELD_NUMBER;
      hash = (53 * hash) + getKIBFINHDCKO().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AdjustTrackingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdjustTrackingInfo)
        raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.internal_static_AdjustTrackingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.internal_static_AdjustTrackingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.class, raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jFAMBDKKDHE_ = "";

        jLKFDDDPPHD_ = "";

        mGDJMEMFBCD_ = "";

        bDOFCOCOCPH_ = "";

        lGMPOGACDHA_ = "";

        kIBFINHDCKO_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.internal_static_AdjustTrackingInfo_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo getDefaultInstanceForType() {
        return raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo build() {
        raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo buildPartial() {
        raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo result = new raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo(this);
        result.jFAMBDKKDHE_ = jFAMBDKKDHE_;
        result.jLKFDDDPPHD_ = jLKFDDDPPHD_;
        result.mGDJMEMFBCD_ = mGDJMEMFBCD_;
        result.bDOFCOCOCPH_ = bDOFCOCOCPH_;
        result.lGMPOGACDHA_ = lGMPOGACDHA_;
        result.kIBFINHDCKO_ = kIBFINHDCKO_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo) {
          return mergeFrom((raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo other) {
        if (other == raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo.getDefaultInstance()) return this;
        if (!other.getJFAMBDKKDHE().isEmpty()) {
          jFAMBDKKDHE_ = other.jFAMBDKKDHE_;
          onChanged();
        }
        if (!other.getJLKFDDDPPHD().isEmpty()) {
          jLKFDDDPPHD_ = other.jLKFDDDPPHD_;
          onChanged();
        }
        if (!other.getMGDJMEMFBCD().isEmpty()) {
          mGDJMEMFBCD_ = other.mGDJMEMFBCD_;
          onChanged();
        }
        if (!other.getBDOFCOCOCPH().isEmpty()) {
          bDOFCOCOCPH_ = other.bDOFCOCOCPH_;
          onChanged();
        }
        if (!other.getLGMPOGACDHA().isEmpty()) {
          lGMPOGACDHA_ = other.lGMPOGACDHA_;
          onChanged();
        }
        if (!other.getKIBFINHDCKO().isEmpty()) {
          kIBFINHDCKO_ = other.kIBFINHDCKO_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jFAMBDKKDHE_ = "";
      /**
       * <code>string JFAMBDKKDHE = 2;</code>
       * @return The jFAMBDKKDHE.
       */
      public java.lang.String getJFAMBDKKDHE() {
        java.lang.Object ref = jFAMBDKKDHE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jFAMBDKKDHE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string JFAMBDKKDHE = 2;</code>
       * @return The bytes for jFAMBDKKDHE.
       */
      public com.google.protobuf.ByteString
          getJFAMBDKKDHEBytes() {
        java.lang.Object ref = jFAMBDKKDHE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jFAMBDKKDHE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string JFAMBDKKDHE = 2;</code>
       * @param value The jFAMBDKKDHE to set.
       * @return This builder for chaining.
       */
      public Builder setJFAMBDKKDHE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jFAMBDKKDHE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string JFAMBDKKDHE = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJFAMBDKKDHE() {
        
        jFAMBDKKDHE_ = getDefaultInstance().getJFAMBDKKDHE();
        onChanged();
        return this;
      }
      /**
       * <code>string JFAMBDKKDHE = 2;</code>
       * @param value The bytes for jFAMBDKKDHE to set.
       * @return This builder for chaining.
       */
      public Builder setJFAMBDKKDHEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jFAMBDKKDHE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jLKFDDDPPHD_ = "";
      /**
       * <code>string JLKFDDDPPHD = 3;</code>
       * @return The jLKFDDDPPHD.
       */
      public java.lang.String getJLKFDDDPPHD() {
        java.lang.Object ref = jLKFDDDPPHD_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jLKFDDDPPHD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string JLKFDDDPPHD = 3;</code>
       * @return The bytes for jLKFDDDPPHD.
       */
      public com.google.protobuf.ByteString
          getJLKFDDDPPHDBytes() {
        java.lang.Object ref = jLKFDDDPPHD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jLKFDDDPPHD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string JLKFDDDPPHD = 3;</code>
       * @param value The jLKFDDDPPHD to set.
       * @return This builder for chaining.
       */
      public Builder setJLKFDDDPPHD(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jLKFDDDPPHD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string JLKFDDDPPHD = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJLKFDDDPPHD() {
        
        jLKFDDDPPHD_ = getDefaultInstance().getJLKFDDDPPHD();
        onChanged();
        return this;
      }
      /**
       * <code>string JLKFDDDPPHD = 3;</code>
       * @param value The bytes for jLKFDDDPPHD to set.
       * @return This builder for chaining.
       */
      public Builder setJLKFDDDPPHDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jLKFDDDPPHD_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mGDJMEMFBCD_ = "";
      /**
       * <code>string MGDJMEMFBCD = 8;</code>
       * @return The mGDJMEMFBCD.
       */
      public java.lang.String getMGDJMEMFBCD() {
        java.lang.Object ref = mGDJMEMFBCD_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mGDJMEMFBCD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MGDJMEMFBCD = 8;</code>
       * @return The bytes for mGDJMEMFBCD.
       */
      public com.google.protobuf.ByteString
          getMGDJMEMFBCDBytes() {
        java.lang.Object ref = mGDJMEMFBCD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mGDJMEMFBCD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MGDJMEMFBCD = 8;</code>
       * @param value The mGDJMEMFBCD to set.
       * @return This builder for chaining.
       */
      public Builder setMGDJMEMFBCD(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mGDJMEMFBCD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MGDJMEMFBCD = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMGDJMEMFBCD() {
        
        mGDJMEMFBCD_ = getDefaultInstance().getMGDJMEMFBCD();
        onChanged();
        return this;
      }
      /**
       * <code>string MGDJMEMFBCD = 8;</code>
       * @param value The bytes for mGDJMEMFBCD to set.
       * @return This builder for chaining.
       */
      public Builder setMGDJMEMFBCDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mGDJMEMFBCD_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bDOFCOCOCPH_ = "";
      /**
       * <code>string BDOFCOCOCPH = 11;</code>
       * @return The bDOFCOCOCPH.
       */
      public java.lang.String getBDOFCOCOCPH() {
        java.lang.Object ref = bDOFCOCOCPH_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bDOFCOCOCPH_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string BDOFCOCOCPH = 11;</code>
       * @return The bytes for bDOFCOCOCPH.
       */
      public com.google.protobuf.ByteString
          getBDOFCOCOCPHBytes() {
        java.lang.Object ref = bDOFCOCOCPH_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bDOFCOCOCPH_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string BDOFCOCOCPH = 11;</code>
       * @param value The bDOFCOCOCPH to set.
       * @return This builder for chaining.
       */
      public Builder setBDOFCOCOCPH(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bDOFCOCOCPH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string BDOFCOCOCPH = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBDOFCOCOCPH() {
        
        bDOFCOCOCPH_ = getDefaultInstance().getBDOFCOCOCPH();
        onChanged();
        return this;
      }
      /**
       * <code>string BDOFCOCOCPH = 11;</code>
       * @param value The bytes for bDOFCOCOCPH to set.
       * @return This builder for chaining.
       */
      public Builder setBDOFCOCOCPHBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bDOFCOCOCPH_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lGMPOGACDHA_ = "";
      /**
       * <code>string LGMPOGACDHA = 13;</code>
       * @return The lGMPOGACDHA.
       */
      public java.lang.String getLGMPOGACDHA() {
        java.lang.Object ref = lGMPOGACDHA_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lGMPOGACDHA_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string LGMPOGACDHA = 13;</code>
       * @return The bytes for lGMPOGACDHA.
       */
      public com.google.protobuf.ByteString
          getLGMPOGACDHABytes() {
        java.lang.Object ref = lGMPOGACDHA_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lGMPOGACDHA_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string LGMPOGACDHA = 13;</code>
       * @param value The lGMPOGACDHA to set.
       * @return This builder for chaining.
       */
      public Builder setLGMPOGACDHA(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lGMPOGACDHA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string LGMPOGACDHA = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearLGMPOGACDHA() {
        
        lGMPOGACDHA_ = getDefaultInstance().getLGMPOGACDHA();
        onChanged();
        return this;
      }
      /**
       * <code>string LGMPOGACDHA = 13;</code>
       * @param value The bytes for lGMPOGACDHA to set.
       * @return This builder for chaining.
       */
      public Builder setLGMPOGACDHABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lGMPOGACDHA_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kIBFINHDCKO_ = "";
      /**
       * <code>string KIBFINHDCKO = 15;</code>
       * @return The kIBFINHDCKO.
       */
      public java.lang.String getKIBFINHDCKO() {
        java.lang.Object ref = kIBFINHDCKO_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kIBFINHDCKO_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string KIBFINHDCKO = 15;</code>
       * @return The bytes for kIBFINHDCKO.
       */
      public com.google.protobuf.ByteString
          getKIBFINHDCKOBytes() {
        java.lang.Object ref = kIBFINHDCKO_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kIBFINHDCKO_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string KIBFINHDCKO = 15;</code>
       * @param value The kIBFINHDCKO to set.
       * @return This builder for chaining.
       */
      public Builder setKIBFINHDCKO(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kIBFINHDCKO_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string KIBFINHDCKO = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearKIBFINHDCKO() {
        
        kIBFINHDCKO_ = getDefaultInstance().getKIBFINHDCKO();
        onChanged();
        return this;
      }
      /**
       * <code>string KIBFINHDCKO = 15;</code>
       * @param value The bytes for kIBFINHDCKO to set.
       * @return This builder for chaining.
       */
      public Builder setKIBFINHDCKOBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kIBFINHDCKO_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdjustTrackingInfo)
    }

    // @@protoc_insertion_point(class_scope:AdjustTrackingInfo)
    private static final raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo();
    }

    public static raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustTrackingInfo>
        PARSER = new com.google.protobuf.AbstractParser<AdjustTrackingInfo>() {
      @java.lang.Override
      public AdjustTrackingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustTrackingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustTrackingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustTrackingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.AdjustTrackingInfoOuterClass.AdjustTrackingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdjustTrackingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdjustTrackingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030AdjustTrackingInfo.proto\"\222\001\n\022AdjustTra" +
      "ckingInfo\022\023\n\013JFAMBDKKDHE\030\002 \001(\t\022\023\n\013JLKFDD" +
      "DPPHD\030\003 \001(\t\022\023\n\013MGDJMEMFBCD\030\010 \001(\t\022\023\n\013BDOF" +
      "COCOCPH\030\013 \001(\t\022\023\n\013LGMPOGACDHA\030\r \001(\t\022\023\n\013KI" +
      "BFINHDCKO\030\017 \001(\tB\033\n\031raidengame.cache.prot" +
      "obufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AdjustTrackingInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AdjustTrackingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdjustTrackingInfo_descriptor,
        new java.lang.String[] { "JFAMBDKKDHE", "JLKFDDDPPHD", "MGDJMEMFBCD", "BDOFCOCOCPH", "LGMPOGACDHA", "KIBFINHDCKO", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
