// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetPlayerTokenReq.proto

package raidengame.cache.protobuf;

public final class GetPlayerTokenReqOuterClass {
  private GetPlayerTokenReqOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetPlayerTokenReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetPlayerTokenReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    java.lang.String getCountryCode();
    /**
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>uint32 platform_type = 2;</code>
     * @return The platformType.
     */
    int getPlatformType();

    /**
     * <code>string account_uid = 3;</code>
     * @return The accountUid.
     */
    java.lang.String getAccountUid();
    /**
     * <code>string account_uid = 3;</code>
     * @return The bytes for accountUid.
     */
    com.google.protobuf.ByteString
        getAccountUidBytes();

    /**
     * <code>string account_token = 4;</code>
     * @return The accountToken.
     */
    java.lang.String getAccountToken();
    /**
     * <code>string account_token = 4;</code>
     * @return The bytes for accountToken.
     */
    com.google.protobuf.ByteString
        getAccountTokenBytes();

    /**
     * <code>string client_ip_str = 5;</code>
     * @return The clientIpStr.
     */
    java.lang.String getClientIpStr();
    /**
     * <code>string client_ip_str = 5;</code>
     * @return The bytes for clientIpStr.
     */
    com.google.protobuf.ByteString
        getClientIpStrBytes();

    /**
     * <code>uint32 uid = 6;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>uint32 account_type = 8;</code>
     * @return The accountType.
     */
    int getAccountType();

    /**
     * <code>string account_ext = 9;</code>
     * @return The accountExt.
     */
    java.lang.String getAccountExt();
    /**
     * <code>string account_ext = 9;</code>
     * @return The bytes for accountExt.
     */
    com.google.protobuf.ByteString
        getAccountExtBytes();

    /**
     * <code>string psn_id = 10;</code>
     * @return The psnId.
     */
    java.lang.String getPsnId();
    /**
     * <code>string psn_id = 10;</code>
     * @return The bytes for psnId.
     */
    com.google.protobuf.ByteString
        getPsnIdBytes();

    /**
     * <code>uint32 sub_channel_id = 11;</code>
     * @return The subChannelId.
     */
    int getSubChannelId();

    /**
     * <code>uint32 minors_reg_min_age = 12;</code>
     * @return The minorsRegMinAge.
     */
    int getMinorsRegMinAge();

    /**
     * <code>string online_id = 13;</code>
     * @return The onlineId.
     */
    java.lang.String getOnlineId();
    /**
     * <code>string online_id = 13;</code>
     * @return The bytes for onlineId.
     */
    com.google.protobuf.ByteString
        getOnlineIdBytes();

    /**
     * <code>bool is_guest = 14;</code>
     * @return The isGuest.
     */
    boolean getIsGuest();

    /**
     * <code>uint32 channel_id = 15;</code>
     * @return The channelId.
     */
    int getChannelId();

    /**
     * <code>string client_rand_key = 94;</code>
     * @return The clientRandKey.
     */
    java.lang.String getClientRandKey();
    /**
     * <code>string client_rand_key = 94;</code>
     * @return The bytes for clientRandKey.
     */
    com.google.protobuf.ByteString
        getClientRandKeyBytes();

    /**
     * <code>uint32 language_type = 168;</code>
     * @return The languageType.
     */
    int getLanguageType();

    /**
     * <code>string birthday = 594;</code>
     * @return The birthday.
     */
    java.lang.String getBirthday();
    /**
     * <code>string birthday = 594;</code>
     * @return The bytes for birthday.
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>string psn_region = 1304;</code>
     * @return The psnRegion.
     */
    java.lang.String getPsnRegion();
    /**
     * <code>string psn_region = 1304;</code>
     * @return The bytes for psnRegion.
     */
    com.google.protobuf.ByteString
        getPsnRegionBytes();

    /**
     * <code>uint32 key_id = 1485;</code>
     * @return The keyId.
     */
    int getKeyId();

    /**
     * <code>string auth_appid = 1528;</code>
     * @return The authAppid.
     */
    java.lang.String getAuthAppid();
    /**
     * <code>string auth_appid = 1528;</code>
     * @return The bytes for authAppid.
     */
    com.google.protobuf.ByteString
        getAuthAppidBytes();

    /**
     * <code>uint32 cloudClientIp = 1686;</code>
     * @return The cloudClientIp.
     */
    int getCloudClientIp();

    /**
     * <code>uint32 sign_type = 1730;</code>
     * @return The signType.
     */
    int getSignType();

    /**
     * <code>uint32 authkey_ver = 1776;</code>
     * @return The authkeyVer.
     */
    int getAuthkeyVer();

    /**
     * <code>string connect_gate_ticket = 1804;</code>
     * @return The connectGateTicket.
     */
    java.lang.String getConnectGateTicket();
    /**
     * <code>string connect_gate_ticket = 1804;</code>
     * @return The bytes for connectGateTicket.
     */
    com.google.protobuf.ByteString
        getConnectGateTicketBytes();
  }
  /**
   * <pre>
   * Version: 5.0
   * CmdId: 6013
   * </pre>
   *
   * Protobuf type {@code GetPlayerTokenReq}
   */
  public static final class GetPlayerTokenReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetPlayerTokenReq)
      GetPlayerTokenReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetPlayerTokenReq.newBuilder() to construct.
    private GetPlayerTokenReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetPlayerTokenReq() {
      countryCode_ = "";
      accountUid_ = "";
      accountToken_ = "";
      clientIpStr_ = "";
      accountExt_ = "";
      psnId_ = "";
      onlineId_ = "";
      clientRandKey_ = "";
      birthday_ = "";
      psnRegion_ = "";
      authAppid_ = "";
      connectGateTicket_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetPlayerTokenReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetPlayerTokenReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              countryCode_ = s;
              break;
            }
            case 16: {

              platformType_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              accountUid_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              accountToken_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              clientIpStr_ = s;
              break;
            }
            case 48: {

              uid_ = input.readUInt32();
              break;
            }
            case 64: {

              accountType_ = input.readUInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              accountExt_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              psnId_ = s;
              break;
            }
            case 88: {

              subChannelId_ = input.readUInt32();
              break;
            }
            case 96: {

              minorsRegMinAge_ = input.readUInt32();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              onlineId_ = s;
              break;
            }
            case 112: {

              isGuest_ = input.readBool();
              break;
            }
            case 120: {

              channelId_ = input.readUInt32();
              break;
            }
            case 754: {
              java.lang.String s = input.readStringRequireUtf8();

              clientRandKey_ = s;
              break;
            }
            case 1344: {

              languageType_ = input.readUInt32();
              break;
            }
            case 4754: {
              java.lang.String s = input.readStringRequireUtf8();

              birthday_ = s;
              break;
            }
            case 10434: {
              java.lang.String s = input.readStringRequireUtf8();

              psnRegion_ = s;
              break;
            }
            case 11880: {

              keyId_ = input.readUInt32();
              break;
            }
            case 12226: {
              java.lang.String s = input.readStringRequireUtf8();

              authAppid_ = s;
              break;
            }
            case 13488: {

              cloudClientIp_ = input.readUInt32();
              break;
            }
            case 13840: {

              signType_ = input.readUInt32();
              break;
            }
            case 14208: {

              authkeyVer_ = input.readUInt32();
              break;
            }
            case 14434: {
              java.lang.String s = input.readStringRequireUtf8();

              connectGateTicket_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.internal_static_GetPlayerTokenReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.internal_static_GetPlayerTokenReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.class, raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.Builder.class);
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object countryCode_;
    /**
     * <code>string country_code = 1;</code>
     * @return The countryCode.
     */
    @java.lang.Override
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string country_code = 1;</code>
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_TYPE_FIELD_NUMBER = 2;
    private int platformType_;
    /**
     * <code>uint32 platform_type = 2;</code>
     * @return The platformType.
     */
    @java.lang.Override
    public int getPlatformType() {
      return platformType_;
    }

    public static final int ACCOUNT_UID_FIELD_NUMBER = 3;
    private volatile java.lang.Object accountUid_;
    /**
     * <code>string account_uid = 3;</code>
     * @return The accountUid.
     */
    @java.lang.Override
    public java.lang.String getAccountUid() {
      java.lang.Object ref = accountUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountUid_ = s;
        return s;
      }
    }
    /**
     * <code>string account_uid = 3;</code>
     * @return The bytes for accountUid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountUidBytes() {
      java.lang.Object ref = accountUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_TOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object accountToken_;
    /**
     * <code>string account_token = 4;</code>
     * @return The accountToken.
     */
    @java.lang.Override
    public java.lang.String getAccountToken() {
      java.lang.Object ref = accountToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountToken_ = s;
        return s;
      }
    }
    /**
     * <code>string account_token = 4;</code>
     * @return The bytes for accountToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountTokenBytes() {
      java.lang.Object ref = accountToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_IP_STR_FIELD_NUMBER = 5;
    private volatile java.lang.Object clientIpStr_;
    /**
     * <code>string client_ip_str = 5;</code>
     * @return The clientIpStr.
     */
    @java.lang.Override
    public java.lang.String getClientIpStr() {
      java.lang.Object ref = clientIpStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIpStr_ = s;
        return s;
      }
    }
    /**
     * <code>string client_ip_str = 5;</code>
     * @return The bytes for clientIpStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIpStrBytes() {
      java.lang.Object ref = clientIpStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIpStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 6;
    private int uid_;
    /**
     * <code>uint32 uid = 6;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int ACCOUNT_TYPE_FIELD_NUMBER = 8;
    private int accountType_;
    /**
     * <code>uint32 account_type = 8;</code>
     * @return The accountType.
     */
    @java.lang.Override
    public int getAccountType() {
      return accountType_;
    }

    public static final int ACCOUNT_EXT_FIELD_NUMBER = 9;
    private volatile java.lang.Object accountExt_;
    /**
     * <code>string account_ext = 9;</code>
     * @return The accountExt.
     */
    @java.lang.Override
    public java.lang.String getAccountExt() {
      java.lang.Object ref = accountExt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountExt_ = s;
        return s;
      }
    }
    /**
     * <code>string account_ext = 9;</code>
     * @return The bytes for accountExt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountExtBytes() {
      java.lang.Object ref = accountExt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountExt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PSN_ID_FIELD_NUMBER = 10;
    private volatile java.lang.Object psnId_;
    /**
     * <code>string psn_id = 10;</code>
     * @return The psnId.
     */
    @java.lang.Override
    public java.lang.String getPsnId() {
      java.lang.Object ref = psnId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        psnId_ = s;
        return s;
      }
    }
    /**
     * <code>string psn_id = 10;</code>
     * @return The bytes for psnId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPsnIdBytes() {
      java.lang.Object ref = psnId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psnId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_CHANNEL_ID_FIELD_NUMBER = 11;
    private int subChannelId_;
    /**
     * <code>uint32 sub_channel_id = 11;</code>
     * @return The subChannelId.
     */
    @java.lang.Override
    public int getSubChannelId() {
      return subChannelId_;
    }

    public static final int MINORS_REG_MIN_AGE_FIELD_NUMBER = 12;
    private int minorsRegMinAge_;
    /**
     * <code>uint32 minors_reg_min_age = 12;</code>
     * @return The minorsRegMinAge.
     */
    @java.lang.Override
    public int getMinorsRegMinAge() {
      return minorsRegMinAge_;
    }

    public static final int ONLINE_ID_FIELD_NUMBER = 13;
    private volatile java.lang.Object onlineId_;
    /**
     * <code>string online_id = 13;</code>
     * @return The onlineId.
     */
    @java.lang.Override
    public java.lang.String getOnlineId() {
      java.lang.Object ref = onlineId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        onlineId_ = s;
        return s;
      }
    }
    /**
     * <code>string online_id = 13;</code>
     * @return The bytes for onlineId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOnlineIdBytes() {
      java.lang.Object ref = onlineId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        onlineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_GUEST_FIELD_NUMBER = 14;
    private boolean isGuest_;
    /**
     * <code>bool is_guest = 14;</code>
     * @return The isGuest.
     */
    @java.lang.Override
    public boolean getIsGuest() {
      return isGuest_;
    }

    public static final int CHANNEL_ID_FIELD_NUMBER = 15;
    private int channelId_;
    /**
     * <code>uint32 channel_id = 15;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public int getChannelId() {
      return channelId_;
    }

    public static final int CLIENT_RAND_KEY_FIELD_NUMBER = 94;
    private volatile java.lang.Object clientRandKey_;
    /**
     * <code>string client_rand_key = 94;</code>
     * @return The clientRandKey.
     */
    @java.lang.Override
    public java.lang.String getClientRandKey() {
      java.lang.Object ref = clientRandKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientRandKey_ = s;
        return s;
      }
    }
    /**
     * <code>string client_rand_key = 94;</code>
     * @return The bytes for clientRandKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientRandKeyBytes() {
      java.lang.Object ref = clientRandKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientRandKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_TYPE_FIELD_NUMBER = 168;
    private int languageType_;
    /**
     * <code>uint32 language_type = 168;</code>
     * @return The languageType.
     */
    @java.lang.Override
    public int getLanguageType() {
      return languageType_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 594;
    private volatile java.lang.Object birthday_;
    /**
     * <code>string birthday = 594;</code>
     * @return The birthday.
     */
    @java.lang.Override
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthday_ = s;
        return s;
      }
    }
    /**
     * <code>string birthday = 594;</code>
     * @return The bytes for birthday.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PSN_REGION_FIELD_NUMBER = 1304;
    private volatile java.lang.Object psnRegion_;
    /**
     * <code>string psn_region = 1304;</code>
     * @return The psnRegion.
     */
    @java.lang.Override
    public java.lang.String getPsnRegion() {
      java.lang.Object ref = psnRegion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        psnRegion_ = s;
        return s;
      }
    }
    /**
     * <code>string psn_region = 1304;</code>
     * @return The bytes for psnRegion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPsnRegionBytes() {
      java.lang.Object ref = psnRegion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        psnRegion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_ID_FIELD_NUMBER = 1485;
    private int keyId_;
    /**
     * <code>uint32 key_id = 1485;</code>
     * @return The keyId.
     */
    @java.lang.Override
    public int getKeyId() {
      return keyId_;
    }

    public static final int AUTH_APPID_FIELD_NUMBER = 1528;
    private volatile java.lang.Object authAppid_;
    /**
     * <code>string auth_appid = 1528;</code>
     * @return The authAppid.
     */
    @java.lang.Override
    public java.lang.String getAuthAppid() {
      java.lang.Object ref = authAppid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authAppid_ = s;
        return s;
      }
    }
    /**
     * <code>string auth_appid = 1528;</code>
     * @return The bytes for authAppid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthAppidBytes() {
      java.lang.Object ref = authAppid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authAppid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLOUDCLIENTIP_FIELD_NUMBER = 1686;
    private int cloudClientIp_;
    /**
     * <code>uint32 cloudClientIp = 1686;</code>
     * @return The cloudClientIp.
     */
    @java.lang.Override
    public int getCloudClientIp() {
      return cloudClientIp_;
    }

    public static final int SIGN_TYPE_FIELD_NUMBER = 1730;
    private int signType_;
    /**
     * <code>uint32 sign_type = 1730;</code>
     * @return The signType.
     */
    @java.lang.Override
    public int getSignType() {
      return signType_;
    }

    public static final int AUTHKEY_VER_FIELD_NUMBER = 1776;
    private int authkeyVer_;
    /**
     * <code>uint32 authkey_ver = 1776;</code>
     * @return The authkeyVer.
     */
    @java.lang.Override
    public int getAuthkeyVer() {
      return authkeyVer_;
    }

    public static final int CONNECT_GATE_TICKET_FIELD_NUMBER = 1804;
    private volatile java.lang.Object connectGateTicket_;
    /**
     * <code>string connect_gate_ticket = 1804;</code>
     * @return The connectGateTicket.
     */
    @java.lang.Override
    public java.lang.String getConnectGateTicket() {
      java.lang.Object ref = connectGateTicket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectGateTicket_ = s;
        return s;
      }
    }
    /**
     * <code>string connect_gate_ticket = 1804;</code>
     * @return The bytes for connectGateTicket.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnectGateTicketBytes() {
      java.lang.Object ref = connectGateTicket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectGateTicket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, countryCode_);
      }
      if (platformType_ != 0) {
        output.writeUInt32(2, platformType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountUid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accountUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accountToken_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIpStr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientIpStr_);
      }
      if (uid_ != 0) {
        output.writeUInt32(6, uid_);
      }
      if (accountType_ != 0) {
        output.writeUInt32(8, accountType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountExt_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, accountExt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(psnId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, psnId_);
      }
      if (subChannelId_ != 0) {
        output.writeUInt32(11, subChannelId_);
      }
      if (minorsRegMinAge_ != 0) {
        output.writeUInt32(12, minorsRegMinAge_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, onlineId_);
      }
      if (isGuest_ != false) {
        output.writeBool(14, isGuest_);
      }
      if (channelId_ != 0) {
        output.writeUInt32(15, channelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientRandKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 94, clientRandKey_);
      }
      if (languageType_ != 0) {
        output.writeUInt32(168, languageType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthday_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 594, birthday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(psnRegion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1304, psnRegion_);
      }
      if (keyId_ != 0) {
        output.writeUInt32(1485, keyId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authAppid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1528, authAppid_);
      }
      if (cloudClientIp_ != 0) {
        output.writeUInt32(1686, cloudClientIp_);
      }
      if (signType_ != 0) {
        output.writeUInt32(1730, signType_);
      }
      if (authkeyVer_ != 0) {
        output.writeUInt32(1776, authkeyVer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectGateTicket_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1804, connectGateTicket_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(countryCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, countryCode_);
      }
      if (platformType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, platformType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountUid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accountUid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accountToken_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIpStr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientIpStr_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, uid_);
      }
      if (accountType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, accountType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountExt_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, accountExt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(psnId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, psnId_);
      }
      if (subChannelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, subChannelId_);
      }
      if (minorsRegMinAge_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, minorsRegMinAge_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onlineId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, onlineId_);
      }
      if (isGuest_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, isGuest_);
      }
      if (channelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, channelId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientRandKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(94, clientRandKey_);
      }
      if (languageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(168, languageType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthday_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(594, birthday_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(psnRegion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1304, psnRegion_);
      }
      if (keyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1485, keyId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authAppid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1528, authAppid_);
      }
      if (cloudClientIp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1686, cloudClientIp_);
      }
      if (signType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1730, signType_);
      }
      if (authkeyVer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1776, authkeyVer_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectGateTicket_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1804, connectGateTicket_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq other = (raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq) obj;

      if (!getCountryCode()
          .equals(other.getCountryCode())) return false;
      if (getPlatformType()
          != other.getPlatformType()) return false;
      if (!getAccountUid()
          .equals(other.getAccountUid())) return false;
      if (!getAccountToken()
          .equals(other.getAccountToken())) return false;
      if (!getClientIpStr()
          .equals(other.getClientIpStr())) return false;
      if (getUid()
          != other.getUid()) return false;
      if (getAccountType()
          != other.getAccountType()) return false;
      if (!getAccountExt()
          .equals(other.getAccountExt())) return false;
      if (!getPsnId()
          .equals(other.getPsnId())) return false;
      if (getSubChannelId()
          != other.getSubChannelId()) return false;
      if (getMinorsRegMinAge()
          != other.getMinorsRegMinAge()) return false;
      if (!getOnlineId()
          .equals(other.getOnlineId())) return false;
      if (getIsGuest()
          != other.getIsGuest()) return false;
      if (getChannelId()
          != other.getChannelId()) return false;
      if (!getClientRandKey()
          .equals(other.getClientRandKey())) return false;
      if (getLanguageType()
          != other.getLanguageType()) return false;
      if (!getBirthday()
          .equals(other.getBirthday())) return false;
      if (!getPsnRegion()
          .equals(other.getPsnRegion())) return false;
      if (getKeyId()
          != other.getKeyId()) return false;
      if (!getAuthAppid()
          .equals(other.getAuthAppid())) return false;
      if (getCloudClientIp()
          != other.getCloudClientIp()) return false;
      if (getSignType()
          != other.getSignType()) return false;
      if (getAuthkeyVer()
          != other.getAuthkeyVer()) return false;
      if (!getConnectGateTicket()
          .equals(other.getConnectGateTicket())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCountryCode().hashCode();
      hash = (37 * hash) + PLATFORM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformType();
      hash = (37 * hash) + ACCOUNT_UID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountUid().hashCode();
      hash = (37 * hash) + ACCOUNT_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccountToken().hashCode();
      hash = (37 * hash) + CLIENT_IP_STR_FIELD_NUMBER;
      hash = (53 * hash) + getClientIpStr().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + ACCOUNT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountType();
      hash = (37 * hash) + ACCOUNT_EXT_FIELD_NUMBER;
      hash = (53 * hash) + getAccountExt().hashCode();
      hash = (37 * hash) + PSN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPsnId().hashCode();
      hash = (37 * hash) + SUB_CHANNEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSubChannelId();
      hash = (37 * hash) + MINORS_REG_MIN_AGE_FIELD_NUMBER;
      hash = (53 * hash) + getMinorsRegMinAge();
      hash = (37 * hash) + ONLINE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getOnlineId().hashCode();
      hash = (37 * hash) + IS_GUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsGuest());
      hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId();
      hash = (37 * hash) + CLIENT_RAND_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getClientRandKey().hashCode();
      hash = (37 * hash) + LANGUAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguageType();
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBirthday().hashCode();
      hash = (37 * hash) + PSN_REGION_FIELD_NUMBER;
      hash = (53 * hash) + getPsnRegion().hashCode();
      hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyId();
      hash = (37 * hash) + AUTH_APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAuthAppid().hashCode();
      hash = (37 * hash) + CLOUDCLIENTIP_FIELD_NUMBER;
      hash = (53 * hash) + getCloudClientIp();
      hash = (37 * hash) + SIGN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSignType();
      hash = (37 * hash) + AUTHKEY_VER_FIELD_NUMBER;
      hash = (53 * hash) + getAuthkeyVer();
      hash = (37 * hash) + CONNECT_GATE_TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getConnectGateTicket().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Version: 5.0
     * CmdId: 6013
     * </pre>
     *
     * Protobuf type {@code GetPlayerTokenReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetPlayerTokenReq)
        raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.internal_static_GetPlayerTokenReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.internal_static_GetPlayerTokenReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.class, raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        countryCode_ = "";

        platformType_ = 0;

        accountUid_ = "";

        accountToken_ = "";

        clientIpStr_ = "";

        uid_ = 0;

        accountType_ = 0;

        accountExt_ = "";

        psnId_ = "";

        subChannelId_ = 0;

        minorsRegMinAge_ = 0;

        onlineId_ = "";

        isGuest_ = false;

        channelId_ = 0;

        clientRandKey_ = "";

        languageType_ = 0;

        birthday_ = "";

        psnRegion_ = "";

        keyId_ = 0;

        authAppid_ = "";

        cloudClientIp_ = 0;

        signType_ = 0;

        authkeyVer_ = 0;

        connectGateTicket_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.internal_static_GetPlayerTokenReq_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq getDefaultInstanceForType() {
        return raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq build() {
        raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq buildPartial() {
        raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq result = new raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq(this);
        result.countryCode_ = countryCode_;
        result.platformType_ = platformType_;
        result.accountUid_ = accountUid_;
        result.accountToken_ = accountToken_;
        result.clientIpStr_ = clientIpStr_;
        result.uid_ = uid_;
        result.accountType_ = accountType_;
        result.accountExt_ = accountExt_;
        result.psnId_ = psnId_;
        result.subChannelId_ = subChannelId_;
        result.minorsRegMinAge_ = minorsRegMinAge_;
        result.onlineId_ = onlineId_;
        result.isGuest_ = isGuest_;
        result.channelId_ = channelId_;
        result.clientRandKey_ = clientRandKey_;
        result.languageType_ = languageType_;
        result.birthday_ = birthday_;
        result.psnRegion_ = psnRegion_;
        result.keyId_ = keyId_;
        result.authAppid_ = authAppid_;
        result.cloudClientIp_ = cloudClientIp_;
        result.signType_ = signType_;
        result.authkeyVer_ = authkeyVer_;
        result.connectGateTicket_ = connectGateTicket_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq) {
          return mergeFrom((raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq other) {
        if (other == raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq.getDefaultInstance()) return this;
        if (!other.getCountryCode().isEmpty()) {
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (other.getPlatformType() != 0) {
          setPlatformType(other.getPlatformType());
        }
        if (!other.getAccountUid().isEmpty()) {
          accountUid_ = other.accountUid_;
          onChanged();
        }
        if (!other.getAccountToken().isEmpty()) {
          accountToken_ = other.accountToken_;
          onChanged();
        }
        if (!other.getClientIpStr().isEmpty()) {
          clientIpStr_ = other.clientIpStr_;
          onChanged();
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getAccountType() != 0) {
          setAccountType(other.getAccountType());
        }
        if (!other.getAccountExt().isEmpty()) {
          accountExt_ = other.accountExt_;
          onChanged();
        }
        if (!other.getPsnId().isEmpty()) {
          psnId_ = other.psnId_;
          onChanged();
        }
        if (other.getSubChannelId() != 0) {
          setSubChannelId(other.getSubChannelId());
        }
        if (other.getMinorsRegMinAge() != 0) {
          setMinorsRegMinAge(other.getMinorsRegMinAge());
        }
        if (!other.getOnlineId().isEmpty()) {
          onlineId_ = other.onlineId_;
          onChanged();
        }
        if (other.getIsGuest() != false) {
          setIsGuest(other.getIsGuest());
        }
        if (other.getChannelId() != 0) {
          setChannelId(other.getChannelId());
        }
        if (!other.getClientRandKey().isEmpty()) {
          clientRandKey_ = other.clientRandKey_;
          onChanged();
        }
        if (other.getLanguageType() != 0) {
          setLanguageType(other.getLanguageType());
        }
        if (!other.getBirthday().isEmpty()) {
          birthday_ = other.birthday_;
          onChanged();
        }
        if (!other.getPsnRegion().isEmpty()) {
          psnRegion_ = other.psnRegion_;
          onChanged();
        }
        if (other.getKeyId() != 0) {
          setKeyId(other.getKeyId());
        }
        if (!other.getAuthAppid().isEmpty()) {
          authAppid_ = other.authAppid_;
          onChanged();
        }
        if (other.getCloudClientIp() != 0) {
          setCloudClientIp(other.getCloudClientIp());
        }
        if (other.getSignType() != 0) {
          setSignType(other.getSignType());
        }
        if (other.getAuthkeyVer() != 0) {
          setAuthkeyVer(other.getAuthkeyVer());
        }
        if (!other.getConnectGateTicket().isEmpty()) {
          connectGateTicket_ = other.connectGateTicket_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>string country_code = 1;</code>
       * @return The countryCode.
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          countryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country_code = 1;</code>
       * @return The bytes for countryCode.
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country_code = 1;</code>
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountryCode() {
        
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string country_code = 1;</code>
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        countryCode_ = value;
        onChanged();
        return this;
      }

      private int platformType_ ;
      /**
       * <code>uint32 platform_type = 2;</code>
       * @return The platformType.
       */
      @java.lang.Override
      public int getPlatformType() {
        return platformType_;
      }
      /**
       * <code>uint32 platform_type = 2;</code>
       * @param value The platformType to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformType(int value) {
        
        platformType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 platform_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatformType() {
        
        platformType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accountUid_ = "";
      /**
       * <code>string account_uid = 3;</code>
       * @return The accountUid.
       */
      public java.lang.String getAccountUid() {
        java.lang.Object ref = accountUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_uid = 3;</code>
       * @return The bytes for accountUid.
       */
      public com.google.protobuf.ByteString
          getAccountUidBytes() {
        java.lang.Object ref = accountUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_uid = 3;</code>
       * @param value The accountUid to set.
       * @return This builder for chaining.
       */
      public Builder setAccountUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account_uid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountUid() {
        
        accountUid_ = getDefaultInstance().getAccountUid();
        onChanged();
        return this;
      }
      /**
       * <code>string account_uid = 3;</code>
       * @param value The bytes for accountUid to set.
       * @return This builder for chaining.
       */
      public Builder setAccountUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountUid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accountToken_ = "";
      /**
       * <code>string account_token = 4;</code>
       * @return The accountToken.
       */
      public java.lang.String getAccountToken() {
        java.lang.Object ref = accountToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_token = 4;</code>
       * @return The bytes for accountToken.
       */
      public com.google.protobuf.ByteString
          getAccountTokenBytes() {
        java.lang.Object ref = accountToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_token = 4;</code>
       * @param value The accountToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccountToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account_token = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountToken() {
        
        accountToken_ = getDefaultInstance().getAccountToken();
        onChanged();
        return this;
      }
      /**
       * <code>string account_token = 4;</code>
       * @param value The bytes for accountToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccountTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientIpStr_ = "";
      /**
       * <code>string client_ip_str = 5;</code>
       * @return The clientIpStr.
       */
      public java.lang.String getClientIpStr() {
        java.lang.Object ref = clientIpStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIpStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_ip_str = 5;</code>
       * @return The bytes for clientIpStr.
       */
      public com.google.protobuf.ByteString
          getClientIpStrBytes() {
        java.lang.Object ref = clientIpStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIpStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_ip_str = 5;</code>
       * @param value The clientIpStr to set.
       * @return This builder for chaining.
       */
      public Builder setClientIpStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientIpStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip_str = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientIpStr() {
        
        clientIpStr_ = getDefaultInstance().getClientIpStr();
        onChanged();
        return this;
      }
      /**
       * <code>string client_ip_str = 5;</code>
       * @param value The bytes for clientIpStr to set.
       * @return This builder for chaining.
       */
      public Builder setClientIpStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientIpStr_ = value;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>uint32 uid = 6;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>uint32 uid = 6;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uid = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int accountType_ ;
      /**
       * <code>uint32 account_type = 8;</code>
       * @return The accountType.
       */
      @java.lang.Override
      public int getAccountType() {
        return accountType_;
      }
      /**
       * <code>uint32 account_type = 8;</code>
       * @param value The accountType to set.
       * @return This builder for chaining.
       */
      public Builder setAccountType(int value) {
        
        accountType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 account_type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountType() {
        
        accountType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accountExt_ = "";
      /**
       * <code>string account_ext = 9;</code>
       * @return The accountExt.
       */
      public java.lang.String getAccountExt() {
        java.lang.Object ref = accountExt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountExt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_ext = 9;</code>
       * @return The bytes for accountExt.
       */
      public com.google.protobuf.ByteString
          getAccountExtBytes() {
        java.lang.Object ref = accountExt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountExt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_ext = 9;</code>
       * @param value The accountExt to set.
       * @return This builder for chaining.
       */
      public Builder setAccountExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountExt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account_ext = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountExt() {
        
        accountExt_ = getDefaultInstance().getAccountExt();
        onChanged();
        return this;
      }
      /**
       * <code>string account_ext = 9;</code>
       * @param value The bytes for accountExt to set.
       * @return This builder for chaining.
       */
      public Builder setAccountExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountExt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object psnId_ = "";
      /**
       * <code>string psn_id = 10;</code>
       * @return The psnId.
       */
      public java.lang.String getPsnId() {
        java.lang.Object ref = psnId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          psnId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string psn_id = 10;</code>
       * @return The bytes for psnId.
       */
      public com.google.protobuf.ByteString
          getPsnIdBytes() {
        java.lang.Object ref = psnId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          psnId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string psn_id = 10;</code>
       * @param value The psnId to set.
       * @return This builder for chaining.
       */
      public Builder setPsnId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        psnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string psn_id = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPsnId() {
        
        psnId_ = getDefaultInstance().getPsnId();
        onChanged();
        return this;
      }
      /**
       * <code>string psn_id = 10;</code>
       * @param value The bytes for psnId to set.
       * @return This builder for chaining.
       */
      public Builder setPsnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        psnId_ = value;
        onChanged();
        return this;
      }

      private int subChannelId_ ;
      /**
       * <code>uint32 sub_channel_id = 11;</code>
       * @return The subChannelId.
       */
      @java.lang.Override
      public int getSubChannelId() {
        return subChannelId_;
      }
      /**
       * <code>uint32 sub_channel_id = 11;</code>
       * @param value The subChannelId to set.
       * @return This builder for chaining.
       */
      public Builder setSubChannelId(int value) {
        
        subChannelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sub_channel_id = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubChannelId() {
        
        subChannelId_ = 0;
        onChanged();
        return this;
      }

      private int minorsRegMinAge_ ;
      /**
       * <code>uint32 minors_reg_min_age = 12;</code>
       * @return The minorsRegMinAge.
       */
      @java.lang.Override
      public int getMinorsRegMinAge() {
        return minorsRegMinAge_;
      }
      /**
       * <code>uint32 minors_reg_min_age = 12;</code>
       * @param value The minorsRegMinAge to set.
       * @return This builder for chaining.
       */
      public Builder setMinorsRegMinAge(int value) {
        
        minorsRegMinAge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 minors_reg_min_age = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinorsRegMinAge() {
        
        minorsRegMinAge_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object onlineId_ = "";
      /**
       * <code>string online_id = 13;</code>
       * @return The onlineId.
       */
      public java.lang.String getOnlineId() {
        java.lang.Object ref = onlineId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          onlineId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string online_id = 13;</code>
       * @return The bytes for onlineId.
       */
      public com.google.protobuf.ByteString
          getOnlineIdBytes() {
        java.lang.Object ref = onlineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          onlineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string online_id = 13;</code>
       * @param value The onlineId to set.
       * @return This builder for chaining.
       */
      public Builder setOnlineId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        onlineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string online_id = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnlineId() {
        
        onlineId_ = getDefaultInstance().getOnlineId();
        onChanged();
        return this;
      }
      /**
       * <code>string online_id = 13;</code>
       * @param value The bytes for onlineId to set.
       * @return This builder for chaining.
       */
      public Builder setOnlineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        onlineId_ = value;
        onChanged();
        return this;
      }

      private boolean isGuest_ ;
      /**
       * <code>bool is_guest = 14;</code>
       * @return The isGuest.
       */
      @java.lang.Override
      public boolean getIsGuest() {
        return isGuest_;
      }
      /**
       * <code>bool is_guest = 14;</code>
       * @param value The isGuest to set.
       * @return This builder for chaining.
       */
      public Builder setIsGuest(boolean value) {
        
        isGuest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_guest = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsGuest() {
        
        isGuest_ = false;
        onChanged();
        return this;
      }

      private int channelId_ ;
      /**
       * <code>uint32 channel_id = 15;</code>
       * @return The channelId.
       */
      @java.lang.Override
      public int getChannelId() {
        return channelId_;
      }
      /**
       * <code>uint32 channel_id = 15;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(int value) {
        
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 channel_id = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        
        channelId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientRandKey_ = "";
      /**
       * <code>string client_rand_key = 94;</code>
       * @return The clientRandKey.
       */
      public java.lang.String getClientRandKey() {
        java.lang.Object ref = clientRandKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientRandKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_rand_key = 94;</code>
       * @return The bytes for clientRandKey.
       */
      public com.google.protobuf.ByteString
          getClientRandKeyBytes() {
        java.lang.Object ref = clientRandKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientRandKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_rand_key = 94;</code>
       * @param value The clientRandKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientRandKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientRandKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_rand_key = 94;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientRandKey() {
        
        clientRandKey_ = getDefaultInstance().getClientRandKey();
        onChanged();
        return this;
      }
      /**
       * <code>string client_rand_key = 94;</code>
       * @param value The bytes for clientRandKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientRandKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientRandKey_ = value;
        onChanged();
        return this;
      }

      private int languageType_ ;
      /**
       * <code>uint32 language_type = 168;</code>
       * @return The languageType.
       */
      @java.lang.Override
      public int getLanguageType() {
        return languageType_;
      }
      /**
       * <code>uint32 language_type = 168;</code>
       * @param value The languageType to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageType(int value) {
        
        languageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 language_type = 168;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguageType() {
        
        languageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object birthday_ = "";
      /**
       * <code>string birthday = 594;</code>
       * @return The birthday.
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthday_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthday = 594;</code>
       * @return The bytes for birthday.
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthday = 594;</code>
       * @param value The birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 594;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthday() {
        
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>string birthday = 594;</code>
       * @param value The bytes for birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthday_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object psnRegion_ = "";
      /**
       * <code>string psn_region = 1304;</code>
       * @return The psnRegion.
       */
      public java.lang.String getPsnRegion() {
        java.lang.Object ref = psnRegion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          psnRegion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string psn_region = 1304;</code>
       * @return The bytes for psnRegion.
       */
      public com.google.protobuf.ByteString
          getPsnRegionBytes() {
        java.lang.Object ref = psnRegion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          psnRegion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string psn_region = 1304;</code>
       * @param value The psnRegion to set.
       * @return This builder for chaining.
       */
      public Builder setPsnRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        psnRegion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string psn_region = 1304;</code>
       * @return This builder for chaining.
       */
      public Builder clearPsnRegion() {
        
        psnRegion_ = getDefaultInstance().getPsnRegion();
        onChanged();
        return this;
      }
      /**
       * <code>string psn_region = 1304;</code>
       * @param value The bytes for psnRegion to set.
       * @return This builder for chaining.
       */
      public Builder setPsnRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        psnRegion_ = value;
        onChanged();
        return this;
      }

      private int keyId_ ;
      /**
       * <code>uint32 key_id = 1485;</code>
       * @return The keyId.
       */
      @java.lang.Override
      public int getKeyId() {
        return keyId_;
      }
      /**
       * <code>uint32 key_id = 1485;</code>
       * @param value The keyId to set.
       * @return This builder for chaining.
       */
      public Builder setKeyId(int value) {
        
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 key_id = 1485;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyId() {
        
        keyId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object authAppid_ = "";
      /**
       * <code>string auth_appid = 1528;</code>
       * @return The authAppid.
       */
      public java.lang.String getAuthAppid() {
        java.lang.Object ref = authAppid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authAppid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string auth_appid = 1528;</code>
       * @return The bytes for authAppid.
       */
      public com.google.protobuf.ByteString
          getAuthAppidBytes() {
        java.lang.Object ref = authAppid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authAppid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string auth_appid = 1528;</code>
       * @param value The authAppid to set.
       * @return This builder for chaining.
       */
      public Builder setAuthAppid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authAppid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string auth_appid = 1528;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthAppid() {
        
        authAppid_ = getDefaultInstance().getAuthAppid();
        onChanged();
        return this;
      }
      /**
       * <code>string auth_appid = 1528;</code>
       * @param value The bytes for authAppid to set.
       * @return This builder for chaining.
       */
      public Builder setAuthAppidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authAppid_ = value;
        onChanged();
        return this;
      }

      private int cloudClientIp_ ;
      /**
       * <code>uint32 cloudClientIp = 1686;</code>
       * @return The cloudClientIp.
       */
      @java.lang.Override
      public int getCloudClientIp() {
        return cloudClientIp_;
      }
      /**
       * <code>uint32 cloudClientIp = 1686;</code>
       * @param value The cloudClientIp to set.
       * @return This builder for chaining.
       */
      public Builder setCloudClientIp(int value) {
        
        cloudClientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cloudClientIp = 1686;</code>
       * @return This builder for chaining.
       */
      public Builder clearCloudClientIp() {
        
        cloudClientIp_ = 0;
        onChanged();
        return this;
      }

      private int signType_ ;
      /**
       * <code>uint32 sign_type = 1730;</code>
       * @return The signType.
       */
      @java.lang.Override
      public int getSignType() {
        return signType_;
      }
      /**
       * <code>uint32 sign_type = 1730;</code>
       * @param value The signType to set.
       * @return This builder for chaining.
       */
      public Builder setSignType(int value) {
        
        signType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sign_type = 1730;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignType() {
        
        signType_ = 0;
        onChanged();
        return this;
      }

      private int authkeyVer_ ;
      /**
       * <code>uint32 authkey_ver = 1776;</code>
       * @return The authkeyVer.
       */
      @java.lang.Override
      public int getAuthkeyVer() {
        return authkeyVer_;
      }
      /**
       * <code>uint32 authkey_ver = 1776;</code>
       * @param value The authkeyVer to set.
       * @return This builder for chaining.
       */
      public Builder setAuthkeyVer(int value) {
        
        authkeyVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 authkey_ver = 1776;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthkeyVer() {
        
        authkeyVer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object connectGateTicket_ = "";
      /**
       * <code>string connect_gate_ticket = 1804;</code>
       * @return The connectGateTicket.
       */
      public java.lang.String getConnectGateTicket() {
        java.lang.Object ref = connectGateTicket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connectGateTicket_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connect_gate_ticket = 1804;</code>
       * @return The bytes for connectGateTicket.
       */
      public com.google.protobuf.ByteString
          getConnectGateTicketBytes() {
        java.lang.Object ref = connectGateTicket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connectGateTicket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connect_gate_ticket = 1804;</code>
       * @param value The connectGateTicket to set.
       * @return This builder for chaining.
       */
      public Builder setConnectGateTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connectGateTicket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connect_gate_ticket = 1804;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectGateTicket() {
        
        connectGateTicket_ = getDefaultInstance().getConnectGateTicket();
        onChanged();
        return this;
      }
      /**
       * <code>string connect_gate_ticket = 1804;</code>
       * @param value The bytes for connectGateTicket to set.
       * @return This builder for chaining.
       */
      public Builder setConnectGateTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connectGateTicket_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetPlayerTokenReq)
    }

    // @@protoc_insertion_point(class_scope:GetPlayerTokenReq)
    private static final raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq();
    }

    public static raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetPlayerTokenReq>
        PARSER = new com.google.protobuf.AbstractParser<GetPlayerTokenReq>() {
      @java.lang.Override
      public GetPlayerTokenReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetPlayerTokenReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetPlayerTokenReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetPlayerTokenReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.GetPlayerTokenReqOuterClass.GetPlayerTokenReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPlayerTokenReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPlayerTokenReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027GetPlayerTokenReq.proto\"\227\004\n\021GetPlayerT" +
      "okenReq\022\024\n\014country_code\030\001 \001(\t\022\025\n\rplatfor" +
      "m_type\030\002 \001(\r\022\023\n\013account_uid\030\003 \001(\t\022\025\n\racc" +
      "ount_token\030\004 \001(\t\022\025\n\rclient_ip_str\030\005 \001(\t\022" +
      "\013\n\003uid\030\006 \001(\r\022\024\n\014account_type\030\010 \001(\r\022\023\n\013ac" +
      "count_ext\030\t \001(\t\022\016\n\006psn_id\030\n \001(\t\022\026\n\016sub_c" +
      "hannel_id\030\013 \001(\r\022\032\n\022minors_reg_min_age\030\014 " +
      "\001(\r\022\021\n\tonline_id\030\r \001(\t\022\020\n\010is_guest\030\016 \001(\010" +
      "\022\022\n\nchannel_id\030\017 \001(\r\022\027\n\017client_rand_key\030" +
      "^ \001(\t\022\026\n\rlanguage_type\030\250\001 \001(\r\022\021\n\010birthda" +
      "y\030\322\004 \001(\t\022\023\n\npsn_region\030\230\n \001(\t\022\017\n\006key_id\030" +
      "\315\013 \001(\r\022\023\n\nauth_appid\030\370\013 \001(\t\022\026\n\rcloudClie" +
      "ntIp\030\226\r \001(\r\022\022\n\tsign_type\030\302\r \001(\r\022\024\n\013authk" +
      "ey_ver\030\360\r \001(\r\022\034\n\023connect_gate_ticket\030\214\016 " +
      "\001(\tB\033\n\031raidengame.cache.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetPlayerTokenReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetPlayerTokenReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPlayerTokenReq_descriptor,
        new java.lang.String[] { "CountryCode", "PlatformType", "AccountUid", "AccountToken", "ClientIpStr", "Uid", "AccountType", "AccountExt", "PsnId", "SubChannelId", "MinorsRegMinAge", "OnlineId", "IsGuest", "ChannelId", "ClientRandKey", "LanguageType", "Birthday", "PsnRegion", "KeyId", "AuthAppid", "CloudClientIp", "SignType", "AuthkeyVer", "ConnectGateTicket", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
