// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PingReq.proto

package raidengame.cache.protobuf;

public final class PingReqOuterClass {
  private PingReqOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes sc_data = 2;</code>
     * @return The scData.
     */
    com.google.protobuf.ByteString getScData();

    /**
     * <code>uint64 timestamp_v2 = 3;</code>
     * @return The timestampV2.
     */
    long getTimestampV2();

    /**
     * <code>uint32 client_time = 4;</code>
     * @return The clientTime.
     */
    int getClientTime();

    /**
     * <code>double total_tick_time = 7;</code>
     * @return The totalTickTime.
     */
    double getTotalTickTime();

    /**
     * <code>float ue_time = 8;</code>
     * @return The ueTime.
     */
    float getUeTime();

    /**
     * <code>uint32 fps = 10;</code>
     * @return The fps.
     */
    int getFps();

    /**
     * <code>bytes PDHFGJIBCLA = 13;</code>
     * @return The pDHFGJIBCLA.
     */
    com.google.protobuf.ByteString getPDHFGJIBCLA();

    /**
     * <code>uint32 seq = 15;</code>
     * @return The seq.
     */
    int getSeq();
  }
  /**
   * <pre>
   * Version: 5.0.0
   * CmdId: 5983
   * </pre>
   *
   * Protobuf type {@code PingReq}
   */
  public static final class PingReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingReq)
      PingReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingReq.newBuilder() to construct.
    private PingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingReq() {
      scData_ = com.google.protobuf.ByteString.EMPTY;
      pDHFGJIBCLA_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PingReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {

              scData_ = input.readBytes();
              break;
            }
            case 24: {

              timestampV2_ = input.readUInt64();
              break;
            }
            case 32: {

              clientTime_ = input.readUInt32();
              break;
            }
            case 57: {

              totalTickTime_ = input.readDouble();
              break;
            }
            case 69: {

              ueTime_ = input.readFloat();
              break;
            }
            case 80: {

              fps_ = input.readUInt32();
              break;
            }
            case 106: {

              pDHFGJIBCLA_ = input.readBytes();
              break;
            }
            case 120: {

              seq_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.PingReqOuterClass.internal_static_PingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.PingReqOuterClass.internal_static_PingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.PingReqOuterClass.PingReq.class, raidengame.cache.protobuf.PingReqOuterClass.PingReq.Builder.class);
    }

    public static final int SC_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString scData_;
    /**
     * <code>bytes sc_data = 2;</code>
     * @return The scData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getScData() {
      return scData_;
    }

    public static final int TIMESTAMP_V2_FIELD_NUMBER = 3;
    private long timestampV2_;
    /**
     * <code>uint64 timestamp_v2 = 3;</code>
     * @return The timestampV2.
     */
    @java.lang.Override
    public long getTimestampV2() {
      return timestampV2_;
    }

    public static final int CLIENT_TIME_FIELD_NUMBER = 4;
    private int clientTime_;
    /**
     * <code>uint32 client_time = 4;</code>
     * @return The clientTime.
     */
    @java.lang.Override
    public int getClientTime() {
      return clientTime_;
    }

    public static final int TOTAL_TICK_TIME_FIELD_NUMBER = 7;
    private double totalTickTime_;
    /**
     * <code>double total_tick_time = 7;</code>
     * @return The totalTickTime.
     */
    @java.lang.Override
    public double getTotalTickTime() {
      return totalTickTime_;
    }

    public static final int UE_TIME_FIELD_NUMBER = 8;
    private float ueTime_;
    /**
     * <code>float ue_time = 8;</code>
     * @return The ueTime.
     */
    @java.lang.Override
    public float getUeTime() {
      return ueTime_;
    }

    public static final int FPS_FIELD_NUMBER = 10;
    private int fps_;
    /**
     * <code>uint32 fps = 10;</code>
     * @return The fps.
     */
    @java.lang.Override
    public int getFps() {
      return fps_;
    }

    public static final int PDHFGJIBCLA_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString pDHFGJIBCLA_;
    /**
     * <code>bytes PDHFGJIBCLA = 13;</code>
     * @return The pDHFGJIBCLA.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPDHFGJIBCLA() {
      return pDHFGJIBCLA_;
    }

    public static final int SEQ_FIELD_NUMBER = 15;
    private int seq_;
    /**
     * <code>uint32 seq = 15;</code>
     * @return The seq.
     */
    @java.lang.Override
    public int getSeq() {
      return seq_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!scData_.isEmpty()) {
        output.writeBytes(2, scData_);
      }
      if (timestampV2_ != 0L) {
        output.writeUInt64(3, timestampV2_);
      }
      if (clientTime_ != 0) {
        output.writeUInt32(4, clientTime_);
      }
      if (java.lang.Double.doubleToRawLongBits(totalTickTime_) != 0) {
        output.writeDouble(7, totalTickTime_);
      }
      if (java.lang.Float.floatToRawIntBits(ueTime_) != 0) {
        output.writeFloat(8, ueTime_);
      }
      if (fps_ != 0) {
        output.writeUInt32(10, fps_);
      }
      if (!pDHFGJIBCLA_.isEmpty()) {
        output.writeBytes(13, pDHFGJIBCLA_);
      }
      if (seq_ != 0) {
        output.writeUInt32(15, seq_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!scData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, scData_);
      }
      if (timestampV2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestampV2_);
      }
      if (clientTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, clientTime_);
      }
      if (java.lang.Double.doubleToRawLongBits(totalTickTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, totalTickTime_);
      }
      if (java.lang.Float.floatToRawIntBits(ueTime_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, ueTime_);
      }
      if (fps_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, fps_);
      }
      if (!pDHFGJIBCLA_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, pDHFGJIBCLA_);
      }
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, seq_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.PingReqOuterClass.PingReq)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.PingReqOuterClass.PingReq other = (raidengame.cache.protobuf.PingReqOuterClass.PingReq) obj;

      if (!getScData()
          .equals(other.getScData())) return false;
      if (getTimestampV2()
          != other.getTimestampV2()) return false;
      if (getClientTime()
          != other.getClientTime()) return false;
      if (java.lang.Double.doubleToLongBits(getTotalTickTime())
          != java.lang.Double.doubleToLongBits(
              other.getTotalTickTime())) return false;
      if (java.lang.Float.floatToIntBits(getUeTime())
          != java.lang.Float.floatToIntBits(
              other.getUeTime())) return false;
      if (getFps()
          != other.getFps()) return false;
      if (!getPDHFGJIBCLA()
          .equals(other.getPDHFGJIBCLA())) return false;
      if (getSeq()
          != other.getSeq()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SC_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getScData().hashCode();
      hash = (37 * hash) + TIMESTAMP_V2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampV2());
      hash = (37 * hash) + CLIENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getClientTime();
      hash = (37 * hash) + TOTAL_TICK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalTickTime()));
      hash = (37 * hash) + UE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getUeTime());
      hash = (37 * hash) + FPS_FIELD_NUMBER;
      hash = (53 * hash) + getFps();
      hash = (37 * hash) + PDHFGJIBCLA_FIELD_NUMBER;
      hash = (53 * hash) + getPDHFGJIBCLA().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.PingReqOuterClass.PingReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Version: 5.0.0
     * CmdId: 5983
     * </pre>
     *
     * Protobuf type {@code PingReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingReq)
        raidengame.cache.protobuf.PingReqOuterClass.PingReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.PingReqOuterClass.internal_static_PingReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.PingReqOuterClass.internal_static_PingReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.PingReqOuterClass.PingReq.class, raidengame.cache.protobuf.PingReqOuterClass.PingReq.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.PingReqOuterClass.PingReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        scData_ = com.google.protobuf.ByteString.EMPTY;

        timestampV2_ = 0L;

        clientTime_ = 0;

        totalTickTime_ = 0D;

        ueTime_ = 0F;

        fps_ = 0;

        pDHFGJIBCLA_ = com.google.protobuf.ByteString.EMPTY;

        seq_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.PingReqOuterClass.internal_static_PingReq_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PingReqOuterClass.PingReq getDefaultInstanceForType() {
        return raidengame.cache.protobuf.PingReqOuterClass.PingReq.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PingReqOuterClass.PingReq build() {
        raidengame.cache.protobuf.PingReqOuterClass.PingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PingReqOuterClass.PingReq buildPartial() {
        raidengame.cache.protobuf.PingReqOuterClass.PingReq result = new raidengame.cache.protobuf.PingReqOuterClass.PingReq(this);
        result.scData_ = scData_;
        result.timestampV2_ = timestampV2_;
        result.clientTime_ = clientTime_;
        result.totalTickTime_ = totalTickTime_;
        result.ueTime_ = ueTime_;
        result.fps_ = fps_;
        result.pDHFGJIBCLA_ = pDHFGJIBCLA_;
        result.seq_ = seq_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.PingReqOuterClass.PingReq) {
          return mergeFrom((raidengame.cache.protobuf.PingReqOuterClass.PingReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.PingReqOuterClass.PingReq other) {
        if (other == raidengame.cache.protobuf.PingReqOuterClass.PingReq.getDefaultInstance()) return this;
        if (other.getScData() != com.google.protobuf.ByteString.EMPTY) {
          setScData(other.getScData());
        }
        if (other.getTimestampV2() != 0L) {
          setTimestampV2(other.getTimestampV2());
        }
        if (other.getClientTime() != 0) {
          setClientTime(other.getClientTime());
        }
        if (other.getTotalTickTime() != 0D) {
          setTotalTickTime(other.getTotalTickTime());
        }
        if (other.getUeTime() != 0F) {
          setUeTime(other.getUeTime());
        }
        if (other.getFps() != 0) {
          setFps(other.getFps());
        }
        if (other.getPDHFGJIBCLA() != com.google.protobuf.ByteString.EMPTY) {
          setPDHFGJIBCLA(other.getPDHFGJIBCLA());
        }
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.PingReqOuterClass.PingReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.PingReqOuterClass.PingReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString scData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes sc_data = 2;</code>
       * @return The scData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getScData() {
        return scData_;
      }
      /**
       * <code>bytes sc_data = 2;</code>
       * @param value The scData to set.
       * @return This builder for chaining.
       */
      public Builder setScData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes sc_data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScData() {
        
        scData_ = getDefaultInstance().getScData();
        onChanged();
        return this;
      }

      private long timestampV2_ ;
      /**
       * <code>uint64 timestamp_v2 = 3;</code>
       * @return The timestampV2.
       */
      @java.lang.Override
      public long getTimestampV2() {
        return timestampV2_;
      }
      /**
       * <code>uint64 timestamp_v2 = 3;</code>
       * @param value The timestampV2 to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampV2(long value) {
        
        timestampV2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp_v2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampV2() {
        
        timestampV2_ = 0L;
        onChanged();
        return this;
      }

      private int clientTime_ ;
      /**
       * <code>uint32 client_time = 4;</code>
       * @return The clientTime.
       */
      @java.lang.Override
      public int getClientTime() {
        return clientTime_;
      }
      /**
       * <code>uint32 client_time = 4;</code>
       * @param value The clientTime to set.
       * @return This builder for chaining.
       */
      public Builder setClientTime(int value) {
        
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 client_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientTime() {
        
        clientTime_ = 0;
        onChanged();
        return this;
      }

      private double totalTickTime_ ;
      /**
       * <code>double total_tick_time = 7;</code>
       * @return The totalTickTime.
       */
      @java.lang.Override
      public double getTotalTickTime() {
        return totalTickTime_;
      }
      /**
       * <code>double total_tick_time = 7;</code>
       * @param value The totalTickTime to set.
       * @return This builder for chaining.
       */
      public Builder setTotalTickTime(double value) {
        
        totalTickTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double total_tick_time = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalTickTime() {
        
        totalTickTime_ = 0D;
        onChanged();
        return this;
      }

      private float ueTime_ ;
      /**
       * <code>float ue_time = 8;</code>
       * @return The ueTime.
       */
      @java.lang.Override
      public float getUeTime() {
        return ueTime_;
      }
      /**
       * <code>float ue_time = 8;</code>
       * @param value The ueTime to set.
       * @return This builder for chaining.
       */
      public Builder setUeTime(float value) {
        
        ueTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float ue_time = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUeTime() {
        
        ueTime_ = 0F;
        onChanged();
        return this;
      }

      private int fps_ ;
      /**
       * <code>uint32 fps = 10;</code>
       * @return The fps.
       */
      @java.lang.Override
      public int getFps() {
        return fps_;
      }
      /**
       * <code>uint32 fps = 10;</code>
       * @param value The fps to set.
       * @return This builder for chaining.
       */
      public Builder setFps(int value) {
        
        fps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fps = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearFps() {
        
        fps_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pDHFGJIBCLA_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes PDHFGJIBCLA = 13;</code>
       * @return The pDHFGJIBCLA.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPDHFGJIBCLA() {
        return pDHFGJIBCLA_;
      }
      /**
       * <code>bytes PDHFGJIBCLA = 13;</code>
       * @param value The pDHFGJIBCLA to set.
       * @return This builder for chaining.
       */
      public Builder setPDHFGJIBCLA(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pDHFGJIBCLA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes PDHFGJIBCLA = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearPDHFGJIBCLA() {
        
        pDHFGJIBCLA_ = getDefaultInstance().getPDHFGJIBCLA();
        onChanged();
        return this;
      }

      private int seq_ ;
      /**
       * <code>uint32 seq = 15;</code>
       * @return The seq.
       */
      @java.lang.Override
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>uint32 seq = 15;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 seq = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PingReq)
    }

    // @@protoc_insertion_point(class_scope:PingReq)
    private static final raidengame.cache.protobuf.PingReqOuterClass.PingReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.PingReqOuterClass.PingReq();
    }

    public static raidengame.cache.protobuf.PingReqOuterClass.PingReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingReq>
        PARSER = new com.google.protobuf.AbstractParser<PingReq>() {
      @java.lang.Override
      public PingReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.PingReqOuterClass.PingReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPingReq.proto\"\236\001\n\007PingReq\022\017\n\007sc_data\030\002" +
      " \001(\014\022\024\n\014timestamp_v2\030\003 \001(\004\022\023\n\013client_tim" +
      "e\030\004 \001(\r\022\027\n\017total_tick_time\030\007 \001(\001\022\017\n\007ue_t" +
      "ime\030\010 \001(\002\022\013\n\003fps\030\n \001(\r\022\023\n\013PDHFGJIBCLA\030\r " +
      "\001(\014\022\013\n\003seq\030\017 \001(\rB\033\n\031raidengame.cache.pro" +
      "tobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PingReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PingReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingReq_descriptor,
        new java.lang.String[] { "ScData", "TimestampV2", "ClientTime", "TotalTickTime", "UeTime", "Fps", "PDHFGJIBCLA", "Seq", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
