// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerEnterSceneNotify.proto

package raidengame.cache.protobuf;

public final class PlayerEnterSceneNotifyOuterClass {
  private PlayerEnterSceneNotifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerEnterSceneNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerEnterSceneNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_skip_ui = 1;</code>
     * @return The isSkipUi.
     */
    boolean getIsSkipUi();

    /**
     * <code>.Vector prev_pos = 2;</code>
     * @return Whether the prevPos field is set.
     */
    boolean hasPrevPos();
    /**
     * <code>.Vector prev_pos = 2;</code>
     * @return The prevPos.
     */
    raidengame.cache.protobuf.VectorOuterClass.Vector getPrevPos();
    /**
     * <code>.Vector prev_pos = 2;</code>
     */
    raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPrevPosOrBuilder();

    /**
     * <code>uint32 world_level = 3;</code>
     * @return The worldLevel.
     */
    int getWorldLevel();

    /**
     * <code>uint32 target_uid = 4;</code>
     * @return The targetUid.
     */
    int getTargetUid();

    /**
     * <code>uint64 scene_begin_time = 5;</code>
     * @return The sceneBeginTime.
     */
    long getSceneBeginTime();

    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @return A list containing the sceneTagIdList.
     */
    java.util.List<java.lang.Integer> getSceneTagIdListList();
    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @return The count of sceneTagIdList.
     */
    int getSceneTagIdListCount();
    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @param index The index of the element to return.
     * @return The sceneTagIdList at the given index.
     */
    int getSceneTagIdList(int index);

    /**
     * <code>uint32 enter_scene_token = 7;</code>
     * @return The enterSceneToken.
     */
    int getEnterSceneToken();

    /**
     * <code>uint32 dungeon_id = 11;</code>
     * @return The dungeonId.
     */
    int getDungeonId();

    /**
     * <pre>
     * GPJHAEEMCBK
     * </pre>
     *
     * <code>uint32 prev_scene_id = 12;</code>
     * @return The prevSceneId.
     */
    int getPrevSceneId();

    /**
     * <code>.Vector pos = 13;</code>
     * @return Whether the pos field is set.
     */
    boolean hasPos();
    /**
     * <code>.Vector pos = 13;</code>
     * @return The pos.
     */
    raidengame.cache.protobuf.VectorOuterClass.Vector getPos();
    /**
     * <code>.Vector pos = 13;</code>
     */
    raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPosOrBuilder();

    /**
     * <code>uint32 scene_id = 14;</code>
     * @return The sceneId.
     */
    int getSceneId();

    /**
     * <code>uint32 type = 15;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     *CGMAOKBGOHO DFNDKDAFEJO = 96;
     * </pre>
     *
     * <code>uint32 ALJNJKPMOPB = 338;</code>
     * @return The aLJNJKPMOPB.
     */
    int getALJNJKPMOPB();

    /**
     * <code>uint32 EKIBACGBHCJ = 358;</code>
     * @return The eKIBACGBHCJ.
     */
    int getEKIBACGBHCJ();

    /**
     * <code>uint32 KDHNDLANKNI = 464;</code>
     * @return The kDHNDLANKNI.
     */
    int getKDHNDLANKNI();

    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     * @return Whether the mapLayerInfo field is set.
     */
    boolean hasMapLayerInfo();
    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     * @return The mapLayerInfo.
     */
    raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo getMapLayerInfo();
    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     */
    raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder getMapLayerInfoOrBuilder();

    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     * @return Whether the kMDLMKGJIHH field is set.
     */
    boolean hasKMDLMKGJIHH();
    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     * @return The kMDLMKGJIHH.
     */
    raidengame.cache.protobuf.VectorOuterClass.Vector getKMDLMKGJIHH();
    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     */
    raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getKMDLMKGJIHHOrBuilder();

    /**
     * <code>bool is_first_login_enter_scene = 816;</code>
     * @return The isFirstLoginEnterScene.
     */
    boolean getIsFirstLoginEnterScene();

    /**
     * <pre>
     * DDGBKGDECME
     * </pre>
     *
     * <code>uint32 enter_reason = 1148;</code>
     * @return The enterReason.
     */
    int getEnterReason();

    /**
     * <code>string scene_transaction = 1492;</code>
     * @return The sceneTransaction.
     */
    java.lang.String getSceneTransaction();
    /**
     * <code>string scene_transaction = 1492;</code>
     * @return The bytes for sceneTransaction.
     */
    com.google.protobuf.ByteString
        getSceneTransactionBytes();

    /**
     * <code>uint32 create_player_uid = 1696;</code>
     * @return The createPlayerUid.
     */
    int getCreatePlayerUid();

    /**
     * <pre>
     * OKCAGDNDEJN
     * </pre>
     *
     * <code>uint32 world_type = 1870;</code>
     * @return The worldType.
     */
    int getWorldType();
  }
  /**
   * Protobuf type {@code PlayerEnterSceneNotify}
   */
  public static final class PlayerEnterSceneNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerEnterSceneNotify)
      PlayerEnterSceneNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerEnterSceneNotify.newBuilder() to construct.
    private PlayerEnterSceneNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerEnterSceneNotify() {
      sceneTagIdList_ = emptyIntList();
      sceneTransaction_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerEnterSceneNotify();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerEnterSceneNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isSkipUi_ = input.readBool();
              break;
            }
            case 18: {
              raidengame.cache.protobuf.VectorOuterClass.Vector.Builder subBuilder = null;
              if (prevPos_ != null) {
                subBuilder = prevPos_.toBuilder();
              }
              prevPos_ = input.readMessage(raidengame.cache.protobuf.VectorOuterClass.Vector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prevPos_);
                prevPos_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              worldLevel_ = input.readUInt32();
              break;
            }
            case 32: {

              targetUid_ = input.readUInt32();
              break;
            }
            case 40: {

              sceneBeginTime_ = input.readUInt64();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                sceneTagIdList_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              sceneTagIdList_.addInt(input.readUInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                sceneTagIdList_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                sceneTagIdList_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {

              enterSceneToken_ = input.readUInt32();
              break;
            }
            case 88: {

              dungeonId_ = input.readUInt32();
              break;
            }
            case 96: {

              prevSceneId_ = input.readUInt32();
              break;
            }
            case 106: {
              raidengame.cache.protobuf.VectorOuterClass.Vector.Builder subBuilder = null;
              if (pos_ != null) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(raidengame.cache.protobuf.VectorOuterClass.Vector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }

              break;
            }
            case 112: {

              sceneId_ = input.readUInt32();
              break;
            }
            case 120: {

              type_ = input.readUInt32();
              break;
            }
            case 2704: {

              aLJNJKPMOPB_ = input.readUInt32();
              break;
            }
            case 2864: {

              eKIBACGBHCJ_ = input.readUInt32();
              break;
            }
            case 3712: {

              kDHNDLANKNI_ = input.readUInt32();
              break;
            }
            case 5922: {
              raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder subBuilder = null;
              if (mapLayerInfo_ != null) {
                subBuilder = mapLayerInfo_.toBuilder();
              }
              mapLayerInfo_ = input.readMessage(raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mapLayerInfo_);
                mapLayerInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 6210: {
              raidengame.cache.protobuf.VectorOuterClass.Vector.Builder subBuilder = null;
              if (kMDLMKGJIHH_ != null) {
                subBuilder = kMDLMKGJIHH_.toBuilder();
              }
              kMDLMKGJIHH_ = input.readMessage(raidengame.cache.protobuf.VectorOuterClass.Vector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(kMDLMKGJIHH_);
                kMDLMKGJIHH_ = subBuilder.buildPartial();
              }

              break;
            }
            case 6528: {

              isFirstLoginEnterScene_ = input.readBool();
              break;
            }
            case 9184: {

              enterReason_ = input.readUInt32();
              break;
            }
            case 11938: {
              java.lang.String s = input.readStringRequireUtf8();

              sceneTransaction_ = s;
              break;
            }
            case 13568: {

              createPlayerUid_ = input.readUInt32();
              break;
            }
            case 14960: {

              worldType_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          sceneTagIdList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.internal_static_PlayerEnterSceneNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.internal_static_PlayerEnterSceneNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.class, raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.Builder.class);
    }

    public static final int IS_SKIP_UI_FIELD_NUMBER = 1;
    private boolean isSkipUi_;
    /**
     * <code>bool is_skip_ui = 1;</code>
     * @return The isSkipUi.
     */
    @java.lang.Override
    public boolean getIsSkipUi() {
      return isSkipUi_;
    }

    public static final int PREV_POS_FIELD_NUMBER = 2;
    private raidengame.cache.protobuf.VectorOuterClass.Vector prevPos_;
    /**
     * <code>.Vector prev_pos = 2;</code>
     * @return Whether the prevPos field is set.
     */
    @java.lang.Override
    public boolean hasPrevPos() {
      return prevPos_ != null;
    }
    /**
     * <code>.Vector prev_pos = 2;</code>
     * @return The prevPos.
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.Vector getPrevPos() {
      return prevPos_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : prevPos_;
    }
    /**
     * <code>.Vector prev_pos = 2;</code>
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPrevPosOrBuilder() {
      return getPrevPos();
    }

    public static final int WORLD_LEVEL_FIELD_NUMBER = 3;
    private int worldLevel_;
    /**
     * <code>uint32 world_level = 3;</code>
     * @return The worldLevel.
     */
    @java.lang.Override
    public int getWorldLevel() {
      return worldLevel_;
    }

    public static final int TARGET_UID_FIELD_NUMBER = 4;
    private int targetUid_;
    /**
     * <code>uint32 target_uid = 4;</code>
     * @return The targetUid.
     */
    @java.lang.Override
    public int getTargetUid() {
      return targetUid_;
    }

    public static final int SCENE_BEGIN_TIME_FIELD_NUMBER = 5;
    private long sceneBeginTime_;
    /**
     * <code>uint64 scene_begin_time = 5;</code>
     * @return The sceneBeginTime.
     */
    @java.lang.Override
    public long getSceneBeginTime() {
      return sceneBeginTime_;
    }

    public static final int SCENE_TAG_ID_LIST_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList sceneTagIdList_;
    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @return A list containing the sceneTagIdList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getSceneTagIdListList() {
      return sceneTagIdList_;
    }
    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @return The count of sceneTagIdList.
     */
    public int getSceneTagIdListCount() {
      return sceneTagIdList_.size();
    }
    /**
     * <code>repeated uint32 scene_tag_id_list = 6;</code>
     * @param index The index of the element to return.
     * @return The sceneTagIdList at the given index.
     */
    public int getSceneTagIdList(int index) {
      return sceneTagIdList_.getInt(index);
    }
    private int sceneTagIdListMemoizedSerializedSize = -1;

    public static final int ENTER_SCENE_TOKEN_FIELD_NUMBER = 7;
    private int enterSceneToken_;
    /**
     * <code>uint32 enter_scene_token = 7;</code>
     * @return The enterSceneToken.
     */
    @java.lang.Override
    public int getEnterSceneToken() {
      return enterSceneToken_;
    }

    public static final int DUNGEON_ID_FIELD_NUMBER = 11;
    private int dungeonId_;
    /**
     * <code>uint32 dungeon_id = 11;</code>
     * @return The dungeonId.
     */
    @java.lang.Override
    public int getDungeonId() {
      return dungeonId_;
    }

    public static final int PREV_SCENE_ID_FIELD_NUMBER = 12;
    private int prevSceneId_;
    /**
     * <pre>
     * GPJHAEEMCBK
     * </pre>
     *
     * <code>uint32 prev_scene_id = 12;</code>
     * @return The prevSceneId.
     */
    @java.lang.Override
    public int getPrevSceneId() {
      return prevSceneId_;
    }

    public static final int POS_FIELD_NUMBER = 13;
    private raidengame.cache.protobuf.VectorOuterClass.Vector pos_;
    /**
     * <code>.Vector pos = 13;</code>
     * @return Whether the pos field is set.
     */
    @java.lang.Override
    public boolean hasPos() {
      return pos_ != null;
    }
    /**
     * <code>.Vector pos = 13;</code>
     * @return The pos.
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.Vector getPos() {
      return pos_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : pos_;
    }
    /**
     * <code>.Vector pos = 13;</code>
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPosOrBuilder() {
      return getPos();
    }

    public static final int SCENE_ID_FIELD_NUMBER = 14;
    private int sceneId_;
    /**
     * <code>uint32 scene_id = 14;</code>
     * @return The sceneId.
     */
    @java.lang.Override
    public int getSceneId() {
      return sceneId_;
    }

    public static final int TYPE_FIELD_NUMBER = 15;
    private int type_;
    /**
     * <code>uint32 type = 15;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int ALJNJKPMOPB_FIELD_NUMBER = 338;
    private int aLJNJKPMOPB_;
    /**
     * <pre>
     *CGMAOKBGOHO DFNDKDAFEJO = 96;
     * </pre>
     *
     * <code>uint32 ALJNJKPMOPB = 338;</code>
     * @return The aLJNJKPMOPB.
     */
    @java.lang.Override
    public int getALJNJKPMOPB() {
      return aLJNJKPMOPB_;
    }

    public static final int EKIBACGBHCJ_FIELD_NUMBER = 358;
    private int eKIBACGBHCJ_;
    /**
     * <code>uint32 EKIBACGBHCJ = 358;</code>
     * @return The eKIBACGBHCJ.
     */
    @java.lang.Override
    public int getEKIBACGBHCJ() {
      return eKIBACGBHCJ_;
    }

    public static final int KDHNDLANKNI_FIELD_NUMBER = 464;
    private int kDHNDLANKNI_;
    /**
     * <code>uint32 KDHNDLANKNI = 464;</code>
     * @return The kDHNDLANKNI.
     */
    @java.lang.Override
    public int getKDHNDLANKNI() {
      return kDHNDLANKNI_;
    }

    public static final int MAP_LAYER_INFO_FIELD_NUMBER = 740;
    private raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo mapLayerInfo_;
    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     * @return Whether the mapLayerInfo field is set.
     */
    @java.lang.Override
    public boolean hasMapLayerInfo() {
      return mapLayerInfo_ != null;
    }
    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     * @return The mapLayerInfo.
     */
    @java.lang.Override
    public raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo getMapLayerInfo() {
      return mapLayerInfo_ == null ? raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.getDefaultInstance() : mapLayerInfo_;
    }
    /**
     * <pre>
     *GJNOBDELMLF BFPGBNDFGBO = 681;
     * </pre>
     *
     * <code>.MapLayerInfo map_layer_info = 740;</code>
     */
    @java.lang.Override
    public raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder getMapLayerInfoOrBuilder() {
      return getMapLayerInfo();
    }

    public static final int KMDLMKGJIHH_FIELD_NUMBER = 776;
    private raidengame.cache.protobuf.VectorOuterClass.Vector kMDLMKGJIHH_;
    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     * @return Whether the kMDLMKGJIHH field is set.
     */
    @java.lang.Override
    public boolean hasKMDLMKGJIHH() {
      return kMDLMKGJIHH_ != null;
    }
    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     * @return The kMDLMKGJIHH.
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.Vector getKMDLMKGJIHH() {
      return kMDLMKGJIHH_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : kMDLMKGJIHH_;
    }
    /**
     * <code>.Vector KMDLMKGJIHH = 776;</code>
     */
    @java.lang.Override
    public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getKMDLMKGJIHHOrBuilder() {
      return getKMDLMKGJIHH();
    }

    public static final int IS_FIRST_LOGIN_ENTER_SCENE_FIELD_NUMBER = 816;
    private boolean isFirstLoginEnterScene_;
    /**
     * <code>bool is_first_login_enter_scene = 816;</code>
     * @return The isFirstLoginEnterScene.
     */
    @java.lang.Override
    public boolean getIsFirstLoginEnterScene() {
      return isFirstLoginEnterScene_;
    }

    public static final int ENTER_REASON_FIELD_NUMBER = 1148;
    private int enterReason_;
    /**
     * <pre>
     * DDGBKGDECME
     * </pre>
     *
     * <code>uint32 enter_reason = 1148;</code>
     * @return The enterReason.
     */
    @java.lang.Override
    public int getEnterReason() {
      return enterReason_;
    }

    public static final int SCENE_TRANSACTION_FIELD_NUMBER = 1492;
    private volatile java.lang.Object sceneTransaction_;
    /**
     * <code>string scene_transaction = 1492;</code>
     * @return The sceneTransaction.
     */
    @java.lang.Override
    public java.lang.String getSceneTransaction() {
      java.lang.Object ref = sceneTransaction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sceneTransaction_ = s;
        return s;
      }
    }
    /**
     * <code>string scene_transaction = 1492;</code>
     * @return The bytes for sceneTransaction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSceneTransactionBytes() {
      java.lang.Object ref = sceneTransaction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sceneTransaction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_PLAYER_UID_FIELD_NUMBER = 1696;
    private int createPlayerUid_;
    /**
     * <code>uint32 create_player_uid = 1696;</code>
     * @return The createPlayerUid.
     */
    @java.lang.Override
    public int getCreatePlayerUid() {
      return createPlayerUid_;
    }

    public static final int WORLD_TYPE_FIELD_NUMBER = 1870;
    private int worldType_;
    /**
     * <pre>
     * OKCAGDNDEJN
     * </pre>
     *
     * <code>uint32 world_type = 1870;</code>
     * @return The worldType.
     */
    @java.lang.Override
    public int getWorldType() {
      return worldType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (isSkipUi_ != false) {
        output.writeBool(1, isSkipUi_);
      }
      if (prevPos_ != null) {
        output.writeMessage(2, getPrevPos());
      }
      if (worldLevel_ != 0) {
        output.writeUInt32(3, worldLevel_);
      }
      if (targetUid_ != 0) {
        output.writeUInt32(4, targetUid_);
      }
      if (sceneBeginTime_ != 0L) {
        output.writeUInt64(5, sceneBeginTime_);
      }
      if (getSceneTagIdListList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(sceneTagIdListMemoizedSerializedSize);
      }
      for (int i = 0; i < sceneTagIdList_.size(); i++) {
        output.writeUInt32NoTag(sceneTagIdList_.getInt(i));
      }
      if (enterSceneToken_ != 0) {
        output.writeUInt32(7, enterSceneToken_);
      }
      if (dungeonId_ != 0) {
        output.writeUInt32(11, dungeonId_);
      }
      if (prevSceneId_ != 0) {
        output.writeUInt32(12, prevSceneId_);
      }
      if (pos_ != null) {
        output.writeMessage(13, getPos());
      }
      if (sceneId_ != 0) {
        output.writeUInt32(14, sceneId_);
      }
      if (type_ != 0) {
        output.writeUInt32(15, type_);
      }
      if (aLJNJKPMOPB_ != 0) {
        output.writeUInt32(338, aLJNJKPMOPB_);
      }
      if (eKIBACGBHCJ_ != 0) {
        output.writeUInt32(358, eKIBACGBHCJ_);
      }
      if (kDHNDLANKNI_ != 0) {
        output.writeUInt32(464, kDHNDLANKNI_);
      }
      if (mapLayerInfo_ != null) {
        output.writeMessage(740, getMapLayerInfo());
      }
      if (kMDLMKGJIHH_ != null) {
        output.writeMessage(776, getKMDLMKGJIHH());
      }
      if (isFirstLoginEnterScene_ != false) {
        output.writeBool(816, isFirstLoginEnterScene_);
      }
      if (enterReason_ != 0) {
        output.writeUInt32(1148, enterReason_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sceneTransaction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1492, sceneTransaction_);
      }
      if (createPlayerUid_ != 0) {
        output.writeUInt32(1696, createPlayerUid_);
      }
      if (worldType_ != 0) {
        output.writeUInt32(1870, worldType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isSkipUi_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSkipUi_);
      }
      if (prevPos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPrevPos());
      }
      if (worldLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, worldLevel_);
      }
      if (targetUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, targetUid_);
      }
      if (sceneBeginTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sceneBeginTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sceneTagIdList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(sceneTagIdList_.getInt(i));
        }
        size += dataSize;
        if (!getSceneTagIdListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sceneTagIdListMemoizedSerializedSize = dataSize;
      }
      if (enterSceneToken_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, enterSceneToken_);
      }
      if (dungeonId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, dungeonId_);
      }
      if (prevSceneId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, prevSceneId_);
      }
      if (pos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getPos());
      }
      if (sceneId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, sceneId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, type_);
      }
      if (aLJNJKPMOPB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(338, aLJNJKPMOPB_);
      }
      if (eKIBACGBHCJ_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(358, eKIBACGBHCJ_);
      }
      if (kDHNDLANKNI_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(464, kDHNDLANKNI_);
      }
      if (mapLayerInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(740, getMapLayerInfo());
      }
      if (kMDLMKGJIHH_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(776, getKMDLMKGJIHH());
      }
      if (isFirstLoginEnterScene_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(816, isFirstLoginEnterScene_);
      }
      if (enterReason_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1148, enterReason_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sceneTransaction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1492, sceneTransaction_);
      }
      if (createPlayerUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1696, createPlayerUid_);
      }
      if (worldType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1870, worldType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify other = (raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify) obj;

      if (getIsSkipUi()
          != other.getIsSkipUi()) return false;
      if (hasPrevPos() != other.hasPrevPos()) return false;
      if (hasPrevPos()) {
        if (!getPrevPos()
            .equals(other.getPrevPos())) return false;
      }
      if (getWorldLevel()
          != other.getWorldLevel()) return false;
      if (getTargetUid()
          != other.getTargetUid()) return false;
      if (getSceneBeginTime()
          != other.getSceneBeginTime()) return false;
      if (!getSceneTagIdListList()
          .equals(other.getSceneTagIdListList())) return false;
      if (getEnterSceneToken()
          != other.getEnterSceneToken()) return false;
      if (getDungeonId()
          != other.getDungeonId()) return false;
      if (getPrevSceneId()
          != other.getPrevSceneId()) return false;
      if (hasPos() != other.hasPos()) return false;
      if (hasPos()) {
        if (!getPos()
            .equals(other.getPos())) return false;
      }
      if (getSceneId()
          != other.getSceneId()) return false;
      if (getType()
          != other.getType()) return false;
      if (getALJNJKPMOPB()
          != other.getALJNJKPMOPB()) return false;
      if (getEKIBACGBHCJ()
          != other.getEKIBACGBHCJ()) return false;
      if (getKDHNDLANKNI()
          != other.getKDHNDLANKNI()) return false;
      if (hasMapLayerInfo() != other.hasMapLayerInfo()) return false;
      if (hasMapLayerInfo()) {
        if (!getMapLayerInfo()
            .equals(other.getMapLayerInfo())) return false;
      }
      if (hasKMDLMKGJIHH() != other.hasKMDLMKGJIHH()) return false;
      if (hasKMDLMKGJIHH()) {
        if (!getKMDLMKGJIHH()
            .equals(other.getKMDLMKGJIHH())) return false;
      }
      if (getIsFirstLoginEnterScene()
          != other.getIsFirstLoginEnterScene()) return false;
      if (getEnterReason()
          != other.getEnterReason()) return false;
      if (!getSceneTransaction()
          .equals(other.getSceneTransaction())) return false;
      if (getCreatePlayerUid()
          != other.getCreatePlayerUid()) return false;
      if (getWorldType()
          != other.getWorldType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_SKIP_UI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSkipUi());
      if (hasPrevPos()) {
        hash = (37 * hash) + PREV_POS_FIELD_NUMBER;
        hash = (53 * hash) + getPrevPos().hashCode();
      }
      hash = (37 * hash) + WORLD_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getWorldLevel();
      hash = (37 * hash) + TARGET_UID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUid();
      hash = (37 * hash) + SCENE_BEGIN_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSceneBeginTime());
      if (getSceneTagIdListCount() > 0) {
        hash = (37 * hash) + SCENE_TAG_ID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getSceneTagIdListList().hashCode();
      }
      hash = (37 * hash) + ENTER_SCENE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getEnterSceneToken();
      hash = (37 * hash) + DUNGEON_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDungeonId();
      hash = (37 * hash) + PREV_SCENE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPrevSceneId();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      hash = (37 * hash) + SCENE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSceneId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + ALJNJKPMOPB_FIELD_NUMBER;
      hash = (53 * hash) + getALJNJKPMOPB();
      hash = (37 * hash) + EKIBACGBHCJ_FIELD_NUMBER;
      hash = (53 * hash) + getEKIBACGBHCJ();
      hash = (37 * hash) + KDHNDLANKNI_FIELD_NUMBER;
      hash = (53 * hash) + getKDHNDLANKNI();
      if (hasMapLayerInfo()) {
        hash = (37 * hash) + MAP_LAYER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getMapLayerInfo().hashCode();
      }
      if (hasKMDLMKGJIHH()) {
        hash = (37 * hash) + KMDLMKGJIHH_FIELD_NUMBER;
        hash = (53 * hash) + getKMDLMKGJIHH().hashCode();
      }
      hash = (37 * hash) + IS_FIRST_LOGIN_ENTER_SCENE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFirstLoginEnterScene());
      hash = (37 * hash) + ENTER_REASON_FIELD_NUMBER;
      hash = (53 * hash) + getEnterReason();
      hash = (37 * hash) + SCENE_TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getSceneTransaction().hashCode();
      hash = (37 * hash) + CREATE_PLAYER_UID_FIELD_NUMBER;
      hash = (53 * hash) + getCreatePlayerUid();
      hash = (37 * hash) + WORLD_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWorldType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerEnterSceneNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerEnterSceneNotify)
        raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.internal_static_PlayerEnterSceneNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.internal_static_PlayerEnterSceneNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.class, raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isSkipUi_ = false;

        if (prevPosBuilder_ == null) {
          prevPos_ = null;
        } else {
          prevPos_ = null;
          prevPosBuilder_ = null;
        }
        worldLevel_ = 0;

        targetUid_ = 0;

        sceneBeginTime_ = 0L;

        sceneTagIdList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        enterSceneToken_ = 0;

        dungeonId_ = 0;

        prevSceneId_ = 0;

        if (posBuilder_ == null) {
          pos_ = null;
        } else {
          pos_ = null;
          posBuilder_ = null;
        }
        sceneId_ = 0;

        type_ = 0;

        aLJNJKPMOPB_ = 0;

        eKIBACGBHCJ_ = 0;

        kDHNDLANKNI_ = 0;

        if (mapLayerInfoBuilder_ == null) {
          mapLayerInfo_ = null;
        } else {
          mapLayerInfo_ = null;
          mapLayerInfoBuilder_ = null;
        }
        if (kMDLMKGJIHHBuilder_ == null) {
          kMDLMKGJIHH_ = null;
        } else {
          kMDLMKGJIHH_ = null;
          kMDLMKGJIHHBuilder_ = null;
        }
        isFirstLoginEnterScene_ = false;

        enterReason_ = 0;

        sceneTransaction_ = "";

        createPlayerUid_ = 0;

        worldType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.internal_static_PlayerEnterSceneNotify_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify getDefaultInstanceForType() {
        return raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify build() {
        raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify buildPartial() {
        raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify result = new raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify(this);
        int from_bitField0_ = bitField0_;
        result.isSkipUi_ = isSkipUi_;
        if (prevPosBuilder_ == null) {
          result.prevPos_ = prevPos_;
        } else {
          result.prevPos_ = prevPosBuilder_.build();
        }
        result.worldLevel_ = worldLevel_;
        result.targetUid_ = targetUid_;
        result.sceneBeginTime_ = sceneBeginTime_;
        if (((bitField0_ & 0x00000001) != 0)) {
          sceneTagIdList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sceneTagIdList_ = sceneTagIdList_;
        result.enterSceneToken_ = enterSceneToken_;
        result.dungeonId_ = dungeonId_;
        result.prevSceneId_ = prevSceneId_;
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        result.sceneId_ = sceneId_;
        result.type_ = type_;
        result.aLJNJKPMOPB_ = aLJNJKPMOPB_;
        result.eKIBACGBHCJ_ = eKIBACGBHCJ_;
        result.kDHNDLANKNI_ = kDHNDLANKNI_;
        if (mapLayerInfoBuilder_ == null) {
          result.mapLayerInfo_ = mapLayerInfo_;
        } else {
          result.mapLayerInfo_ = mapLayerInfoBuilder_.build();
        }
        if (kMDLMKGJIHHBuilder_ == null) {
          result.kMDLMKGJIHH_ = kMDLMKGJIHH_;
        } else {
          result.kMDLMKGJIHH_ = kMDLMKGJIHHBuilder_.build();
        }
        result.isFirstLoginEnterScene_ = isFirstLoginEnterScene_;
        result.enterReason_ = enterReason_;
        result.sceneTransaction_ = sceneTransaction_;
        result.createPlayerUid_ = createPlayerUid_;
        result.worldType_ = worldType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify) {
          return mergeFrom((raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify other) {
        if (other == raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify.getDefaultInstance()) return this;
        if (other.getIsSkipUi() != false) {
          setIsSkipUi(other.getIsSkipUi());
        }
        if (other.hasPrevPos()) {
          mergePrevPos(other.getPrevPos());
        }
        if (other.getWorldLevel() != 0) {
          setWorldLevel(other.getWorldLevel());
        }
        if (other.getTargetUid() != 0) {
          setTargetUid(other.getTargetUid());
        }
        if (other.getSceneBeginTime() != 0L) {
          setSceneBeginTime(other.getSceneBeginTime());
        }
        if (!other.sceneTagIdList_.isEmpty()) {
          if (sceneTagIdList_.isEmpty()) {
            sceneTagIdList_ = other.sceneTagIdList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSceneTagIdListIsMutable();
            sceneTagIdList_.addAll(other.sceneTagIdList_);
          }
          onChanged();
        }
        if (other.getEnterSceneToken() != 0) {
          setEnterSceneToken(other.getEnterSceneToken());
        }
        if (other.getDungeonId() != 0) {
          setDungeonId(other.getDungeonId());
        }
        if (other.getPrevSceneId() != 0) {
          setPrevSceneId(other.getPrevSceneId());
        }
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        if (other.getSceneId() != 0) {
          setSceneId(other.getSceneId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getALJNJKPMOPB() != 0) {
          setALJNJKPMOPB(other.getALJNJKPMOPB());
        }
        if (other.getEKIBACGBHCJ() != 0) {
          setEKIBACGBHCJ(other.getEKIBACGBHCJ());
        }
        if (other.getKDHNDLANKNI() != 0) {
          setKDHNDLANKNI(other.getKDHNDLANKNI());
        }
        if (other.hasMapLayerInfo()) {
          mergeMapLayerInfo(other.getMapLayerInfo());
        }
        if (other.hasKMDLMKGJIHH()) {
          mergeKMDLMKGJIHH(other.getKMDLMKGJIHH());
        }
        if (other.getIsFirstLoginEnterScene() != false) {
          setIsFirstLoginEnterScene(other.getIsFirstLoginEnterScene());
        }
        if (other.getEnterReason() != 0) {
          setEnterReason(other.getEnterReason());
        }
        if (!other.getSceneTransaction().isEmpty()) {
          sceneTransaction_ = other.sceneTransaction_;
          onChanged();
        }
        if (other.getCreatePlayerUid() != 0) {
          setCreatePlayerUid(other.getCreatePlayerUid());
        }
        if (other.getWorldType() != 0) {
          setWorldType(other.getWorldType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSkipUi_ ;
      /**
       * <code>bool is_skip_ui = 1;</code>
       * @return The isSkipUi.
       */
      @java.lang.Override
      public boolean getIsSkipUi() {
        return isSkipUi_;
      }
      /**
       * <code>bool is_skip_ui = 1;</code>
       * @param value The isSkipUi to set.
       * @return This builder for chaining.
       */
      public Builder setIsSkipUi(boolean value) {
        
        isSkipUi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_skip_ui = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSkipUi() {
        
        isSkipUi_ = false;
        onChanged();
        return this;
      }

      private raidengame.cache.protobuf.VectorOuterClass.Vector prevPos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> prevPosBuilder_;
      /**
       * <code>.Vector prev_pos = 2;</code>
       * @return Whether the prevPos field is set.
       */
      public boolean hasPrevPos() {
        return prevPosBuilder_ != null || prevPos_ != null;
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       * @return The prevPos.
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector getPrevPos() {
        if (prevPosBuilder_ == null) {
          return prevPos_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : prevPos_;
        } else {
          return prevPosBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public Builder setPrevPos(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (prevPosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prevPos_ = value;
          onChanged();
        } else {
          prevPosBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public Builder setPrevPos(
          raidengame.cache.protobuf.VectorOuterClass.Vector.Builder builderForValue) {
        if (prevPosBuilder_ == null) {
          prevPos_ = builderForValue.build();
          onChanged();
        } else {
          prevPosBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public Builder mergePrevPos(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (prevPosBuilder_ == null) {
          if (prevPos_ != null) {
            prevPos_ =
              raidengame.cache.protobuf.VectorOuterClass.Vector.newBuilder(prevPos_).mergeFrom(value).buildPartial();
          } else {
            prevPos_ = value;
          }
          onChanged();
        } else {
          prevPosBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public Builder clearPrevPos() {
        if (prevPosBuilder_ == null) {
          prevPos_ = null;
          onChanged();
        } else {
          prevPos_ = null;
          prevPosBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector.Builder getPrevPosBuilder() {
        
        onChanged();
        return getPrevPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPrevPosOrBuilder() {
        if (prevPosBuilder_ != null) {
          return prevPosBuilder_.getMessageOrBuilder();
        } else {
          return prevPos_ == null ?
              raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : prevPos_;
        }
      }
      /**
       * <code>.Vector prev_pos = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> 
          getPrevPosFieldBuilder() {
        if (prevPosBuilder_ == null) {
          prevPosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder>(
                  getPrevPos(),
                  getParentForChildren(),
                  isClean());
          prevPos_ = null;
        }
        return prevPosBuilder_;
      }

      private int worldLevel_ ;
      /**
       * <code>uint32 world_level = 3;</code>
       * @return The worldLevel.
       */
      @java.lang.Override
      public int getWorldLevel() {
        return worldLevel_;
      }
      /**
       * <code>uint32 world_level = 3;</code>
       * @param value The worldLevel to set.
       * @return This builder for chaining.
       */
      public Builder setWorldLevel(int value) {
        
        worldLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 world_level = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorldLevel() {
        
        worldLevel_ = 0;
        onChanged();
        return this;
      }

      private int targetUid_ ;
      /**
       * <code>uint32 target_uid = 4;</code>
       * @return The targetUid.
       */
      @java.lang.Override
      public int getTargetUid() {
        return targetUid_;
      }
      /**
       * <code>uint32 target_uid = 4;</code>
       * @param value The targetUid to set.
       * @return This builder for chaining.
       */
      public Builder setTargetUid(int value) {
        
        targetUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 target_uid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetUid() {
        
        targetUid_ = 0;
        onChanged();
        return this;
      }

      private long sceneBeginTime_ ;
      /**
       * <code>uint64 scene_begin_time = 5;</code>
       * @return The sceneBeginTime.
       */
      @java.lang.Override
      public long getSceneBeginTime() {
        return sceneBeginTime_;
      }
      /**
       * <code>uint64 scene_begin_time = 5;</code>
       * @param value The sceneBeginTime to set.
       * @return This builder for chaining.
       */
      public Builder setSceneBeginTime(long value) {
        
        sceneBeginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 scene_begin_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneBeginTime() {
        
        sceneBeginTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList sceneTagIdList_ = emptyIntList();
      private void ensureSceneTagIdListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sceneTagIdList_ = mutableCopy(sceneTagIdList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @return A list containing the sceneTagIdList.
       */
      public java.util.List<java.lang.Integer>
          getSceneTagIdListList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(sceneTagIdList_) : sceneTagIdList_;
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @return The count of sceneTagIdList.
       */
      public int getSceneTagIdListCount() {
        return sceneTagIdList_.size();
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @param index The index of the element to return.
       * @return The sceneTagIdList at the given index.
       */
      public int getSceneTagIdList(int index) {
        return sceneTagIdList_.getInt(index);
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @param index The index to set the value at.
       * @param value The sceneTagIdList to set.
       * @return This builder for chaining.
       */
      public Builder setSceneTagIdList(
          int index, int value) {
        ensureSceneTagIdListIsMutable();
        sceneTagIdList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @param value The sceneTagIdList to add.
       * @return This builder for chaining.
       */
      public Builder addSceneTagIdList(int value) {
        ensureSceneTagIdListIsMutable();
        sceneTagIdList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @param values The sceneTagIdList to add.
       * @return This builder for chaining.
       */
      public Builder addAllSceneTagIdList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSceneTagIdListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sceneTagIdList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 scene_tag_id_list = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneTagIdList() {
        sceneTagIdList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int enterSceneToken_ ;
      /**
       * <code>uint32 enter_scene_token = 7;</code>
       * @return The enterSceneToken.
       */
      @java.lang.Override
      public int getEnterSceneToken() {
        return enterSceneToken_;
      }
      /**
       * <code>uint32 enter_scene_token = 7;</code>
       * @param value The enterSceneToken to set.
       * @return This builder for chaining.
       */
      public Builder setEnterSceneToken(int value) {
        
        enterSceneToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 enter_scene_token = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnterSceneToken() {
        
        enterSceneToken_ = 0;
        onChanged();
        return this;
      }

      private int dungeonId_ ;
      /**
       * <code>uint32 dungeon_id = 11;</code>
       * @return The dungeonId.
       */
      @java.lang.Override
      public int getDungeonId() {
        return dungeonId_;
      }
      /**
       * <code>uint32 dungeon_id = 11;</code>
       * @param value The dungeonId to set.
       * @return This builder for chaining.
       */
      public Builder setDungeonId(int value) {
        
        dungeonId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dungeon_id = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDungeonId() {
        
        dungeonId_ = 0;
        onChanged();
        return this;
      }

      private int prevSceneId_ ;
      /**
       * <pre>
       * GPJHAEEMCBK
       * </pre>
       *
       * <code>uint32 prev_scene_id = 12;</code>
       * @return The prevSceneId.
       */
      @java.lang.Override
      public int getPrevSceneId() {
        return prevSceneId_;
      }
      /**
       * <pre>
       * GPJHAEEMCBK
       * </pre>
       *
       * <code>uint32 prev_scene_id = 12;</code>
       * @param value The prevSceneId to set.
       * @return This builder for chaining.
       */
      public Builder setPrevSceneId(int value) {
        
        prevSceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GPJHAEEMCBK
       * </pre>
       *
       * <code>uint32 prev_scene_id = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevSceneId() {
        
        prevSceneId_ = 0;
        onChanged();
        return this;
      }

      private raidengame.cache.protobuf.VectorOuterClass.Vector pos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> posBuilder_;
      /**
       * <code>.Vector pos = 13;</code>
       * @return Whether the pos field is set.
       */
      public boolean hasPos() {
        return posBuilder_ != null || pos_ != null;
      }
      /**
       * <code>.Vector pos = 13;</code>
       * @return The pos.
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public Builder setPos(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public Builder setPos(
          raidengame.cache.protobuf.VectorOuterClass.Vector.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public Builder mergePos(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (posBuilder_ == null) {
          if (pos_ != null) {
            pos_ =
              raidengame.cache.protobuf.VectorOuterClass.Vector.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = null;
          onChanged();
        } else {
          pos_ = null;
          posBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector.Builder getPosBuilder() {
        
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : pos_;
        }
      }
      /**
       * <code>.Vector pos = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }

      private int sceneId_ ;
      /**
       * <code>uint32 scene_id = 14;</code>
       * @return The sceneId.
       */
      @java.lang.Override
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>uint32 scene_id = 14;</code>
       * @param value The sceneId to set.
       * @return This builder for chaining.
       */
      public Builder setSceneId(int value) {
        
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 scene_id = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneId() {
        
        sceneId_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>uint32 type = 15;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>uint32 type = 15;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 type = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int aLJNJKPMOPB_ ;
      /**
       * <pre>
       *CGMAOKBGOHO DFNDKDAFEJO = 96;
       * </pre>
       *
       * <code>uint32 ALJNJKPMOPB = 338;</code>
       * @return The aLJNJKPMOPB.
       */
      @java.lang.Override
      public int getALJNJKPMOPB() {
        return aLJNJKPMOPB_;
      }
      /**
       * <pre>
       *CGMAOKBGOHO DFNDKDAFEJO = 96;
       * </pre>
       *
       * <code>uint32 ALJNJKPMOPB = 338;</code>
       * @param value The aLJNJKPMOPB to set.
       * @return This builder for chaining.
       */
      public Builder setALJNJKPMOPB(int value) {
        
        aLJNJKPMOPB_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *CGMAOKBGOHO DFNDKDAFEJO = 96;
       * </pre>
       *
       * <code>uint32 ALJNJKPMOPB = 338;</code>
       * @return This builder for chaining.
       */
      public Builder clearALJNJKPMOPB() {
        
        aLJNJKPMOPB_ = 0;
        onChanged();
        return this;
      }

      private int eKIBACGBHCJ_ ;
      /**
       * <code>uint32 EKIBACGBHCJ = 358;</code>
       * @return The eKIBACGBHCJ.
       */
      @java.lang.Override
      public int getEKIBACGBHCJ() {
        return eKIBACGBHCJ_;
      }
      /**
       * <code>uint32 EKIBACGBHCJ = 358;</code>
       * @param value The eKIBACGBHCJ to set.
       * @return This builder for chaining.
       */
      public Builder setEKIBACGBHCJ(int value) {
        
        eKIBACGBHCJ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 EKIBACGBHCJ = 358;</code>
       * @return This builder for chaining.
       */
      public Builder clearEKIBACGBHCJ() {
        
        eKIBACGBHCJ_ = 0;
        onChanged();
        return this;
      }

      private int kDHNDLANKNI_ ;
      /**
       * <code>uint32 KDHNDLANKNI = 464;</code>
       * @return The kDHNDLANKNI.
       */
      @java.lang.Override
      public int getKDHNDLANKNI() {
        return kDHNDLANKNI_;
      }
      /**
       * <code>uint32 KDHNDLANKNI = 464;</code>
       * @param value The kDHNDLANKNI to set.
       * @return This builder for chaining.
       */
      public Builder setKDHNDLANKNI(int value) {
        
        kDHNDLANKNI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 KDHNDLANKNI = 464;</code>
       * @return This builder for chaining.
       */
      public Builder clearKDHNDLANKNI() {
        
        kDHNDLANKNI_ = 0;
        onChanged();
        return this;
      }

      private raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo mapLayerInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder> mapLayerInfoBuilder_;
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       * @return Whether the mapLayerInfo field is set.
       */
      public boolean hasMapLayerInfo() {
        return mapLayerInfoBuilder_ != null || mapLayerInfo_ != null;
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       * @return The mapLayerInfo.
       */
      public raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo getMapLayerInfo() {
        if (mapLayerInfoBuilder_ == null) {
          return mapLayerInfo_ == null ? raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.getDefaultInstance() : mapLayerInfo_;
        } else {
          return mapLayerInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public Builder setMapLayerInfo(raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo value) {
        if (mapLayerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mapLayerInfo_ = value;
          onChanged();
        } else {
          mapLayerInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public Builder setMapLayerInfo(
          raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder builderForValue) {
        if (mapLayerInfoBuilder_ == null) {
          mapLayerInfo_ = builderForValue.build();
          onChanged();
        } else {
          mapLayerInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public Builder mergeMapLayerInfo(raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo value) {
        if (mapLayerInfoBuilder_ == null) {
          if (mapLayerInfo_ != null) {
            mapLayerInfo_ =
              raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.newBuilder(mapLayerInfo_).mergeFrom(value).buildPartial();
          } else {
            mapLayerInfo_ = value;
          }
          onChanged();
        } else {
          mapLayerInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public Builder clearMapLayerInfo() {
        if (mapLayerInfoBuilder_ == null) {
          mapLayerInfo_ = null;
          onChanged();
        } else {
          mapLayerInfo_ = null;
          mapLayerInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder getMapLayerInfoBuilder() {
        
        onChanged();
        return getMapLayerInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      public raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder getMapLayerInfoOrBuilder() {
        if (mapLayerInfoBuilder_ != null) {
          return mapLayerInfoBuilder_.getMessageOrBuilder();
        } else {
          return mapLayerInfo_ == null ?
              raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.getDefaultInstance() : mapLayerInfo_;
        }
      }
      /**
       * <pre>
       *GJNOBDELMLF BFPGBNDFGBO = 681;
       * </pre>
       *
       * <code>.MapLayerInfo map_layer_info = 740;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder> 
          getMapLayerInfoFieldBuilder() {
        if (mapLayerInfoBuilder_ == null) {
          mapLayerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfo.Builder, raidengame.cache.protobuf.MapLayerInfoOuterClass.MapLayerInfoOrBuilder>(
                  getMapLayerInfo(),
                  getParentForChildren(),
                  isClean());
          mapLayerInfo_ = null;
        }
        return mapLayerInfoBuilder_;
      }

      private raidengame.cache.protobuf.VectorOuterClass.Vector kMDLMKGJIHH_;
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> kMDLMKGJIHHBuilder_;
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       * @return Whether the kMDLMKGJIHH field is set.
       */
      public boolean hasKMDLMKGJIHH() {
        return kMDLMKGJIHHBuilder_ != null || kMDLMKGJIHH_ != null;
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       * @return The kMDLMKGJIHH.
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector getKMDLMKGJIHH() {
        if (kMDLMKGJIHHBuilder_ == null) {
          return kMDLMKGJIHH_ == null ? raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : kMDLMKGJIHH_;
        } else {
          return kMDLMKGJIHHBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public Builder setKMDLMKGJIHH(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (kMDLMKGJIHHBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kMDLMKGJIHH_ = value;
          onChanged();
        } else {
          kMDLMKGJIHHBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public Builder setKMDLMKGJIHH(
          raidengame.cache.protobuf.VectorOuterClass.Vector.Builder builderForValue) {
        if (kMDLMKGJIHHBuilder_ == null) {
          kMDLMKGJIHH_ = builderForValue.build();
          onChanged();
        } else {
          kMDLMKGJIHHBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public Builder mergeKMDLMKGJIHH(raidengame.cache.protobuf.VectorOuterClass.Vector value) {
        if (kMDLMKGJIHHBuilder_ == null) {
          if (kMDLMKGJIHH_ != null) {
            kMDLMKGJIHH_ =
              raidengame.cache.protobuf.VectorOuterClass.Vector.newBuilder(kMDLMKGJIHH_).mergeFrom(value).buildPartial();
          } else {
            kMDLMKGJIHH_ = value;
          }
          onChanged();
        } else {
          kMDLMKGJIHHBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public Builder clearKMDLMKGJIHH() {
        if (kMDLMKGJIHHBuilder_ == null) {
          kMDLMKGJIHH_ = null;
          onChanged();
        } else {
          kMDLMKGJIHH_ = null;
          kMDLMKGJIHHBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.Vector.Builder getKMDLMKGJIHHBuilder() {
        
        onChanged();
        return getKMDLMKGJIHHFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      public raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder getKMDLMKGJIHHOrBuilder() {
        if (kMDLMKGJIHHBuilder_ != null) {
          return kMDLMKGJIHHBuilder_.getMessageOrBuilder();
        } else {
          return kMDLMKGJIHH_ == null ?
              raidengame.cache.protobuf.VectorOuterClass.Vector.getDefaultInstance() : kMDLMKGJIHH_;
        }
      }
      /**
       * <code>.Vector KMDLMKGJIHH = 776;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder> 
          getKMDLMKGJIHHFieldBuilder() {
        if (kMDLMKGJIHHBuilder_ == null) {
          kMDLMKGJIHHBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raidengame.cache.protobuf.VectorOuterClass.Vector, raidengame.cache.protobuf.VectorOuterClass.Vector.Builder, raidengame.cache.protobuf.VectorOuterClass.VectorOrBuilder>(
                  getKMDLMKGJIHH(),
                  getParentForChildren(),
                  isClean());
          kMDLMKGJIHH_ = null;
        }
        return kMDLMKGJIHHBuilder_;
      }

      private boolean isFirstLoginEnterScene_ ;
      /**
       * <code>bool is_first_login_enter_scene = 816;</code>
       * @return The isFirstLoginEnterScene.
       */
      @java.lang.Override
      public boolean getIsFirstLoginEnterScene() {
        return isFirstLoginEnterScene_;
      }
      /**
       * <code>bool is_first_login_enter_scene = 816;</code>
       * @param value The isFirstLoginEnterScene to set.
       * @return This builder for chaining.
       */
      public Builder setIsFirstLoginEnterScene(boolean value) {
        
        isFirstLoginEnterScene_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_first_login_enter_scene = 816;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFirstLoginEnterScene() {
        
        isFirstLoginEnterScene_ = false;
        onChanged();
        return this;
      }

      private int enterReason_ ;
      /**
       * <pre>
       * DDGBKGDECME
       * </pre>
       *
       * <code>uint32 enter_reason = 1148;</code>
       * @return The enterReason.
       */
      @java.lang.Override
      public int getEnterReason() {
        return enterReason_;
      }
      /**
       * <pre>
       * DDGBKGDECME
       * </pre>
       *
       * <code>uint32 enter_reason = 1148;</code>
       * @param value The enterReason to set.
       * @return This builder for chaining.
       */
      public Builder setEnterReason(int value) {
        
        enterReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DDGBKGDECME
       * </pre>
       *
       * <code>uint32 enter_reason = 1148;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnterReason() {
        
        enterReason_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sceneTransaction_ = "";
      /**
       * <code>string scene_transaction = 1492;</code>
       * @return The sceneTransaction.
       */
      public java.lang.String getSceneTransaction() {
        java.lang.Object ref = sceneTransaction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sceneTransaction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string scene_transaction = 1492;</code>
       * @return The bytes for sceneTransaction.
       */
      public com.google.protobuf.ByteString
          getSceneTransactionBytes() {
        java.lang.Object ref = sceneTransaction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sceneTransaction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string scene_transaction = 1492;</code>
       * @param value The sceneTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setSceneTransaction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sceneTransaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string scene_transaction = 1492;</code>
       * @return This builder for chaining.
       */
      public Builder clearSceneTransaction() {
        
        sceneTransaction_ = getDefaultInstance().getSceneTransaction();
        onChanged();
        return this;
      }
      /**
       * <code>string scene_transaction = 1492;</code>
       * @param value The bytes for sceneTransaction to set.
       * @return This builder for chaining.
       */
      public Builder setSceneTransactionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sceneTransaction_ = value;
        onChanged();
        return this;
      }

      private int createPlayerUid_ ;
      /**
       * <code>uint32 create_player_uid = 1696;</code>
       * @return The createPlayerUid.
       */
      @java.lang.Override
      public int getCreatePlayerUid() {
        return createPlayerUid_;
      }
      /**
       * <code>uint32 create_player_uid = 1696;</code>
       * @param value The createPlayerUid to set.
       * @return This builder for chaining.
       */
      public Builder setCreatePlayerUid(int value) {
        
        createPlayerUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 create_player_uid = 1696;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatePlayerUid() {
        
        createPlayerUid_ = 0;
        onChanged();
        return this;
      }

      private int worldType_ ;
      /**
       * <pre>
       * OKCAGDNDEJN
       * </pre>
       *
       * <code>uint32 world_type = 1870;</code>
       * @return The worldType.
       */
      @java.lang.Override
      public int getWorldType() {
        return worldType_;
      }
      /**
       * <pre>
       * OKCAGDNDEJN
       * </pre>
       *
       * <code>uint32 world_type = 1870;</code>
       * @param value The worldType to set.
       * @return This builder for chaining.
       */
      public Builder setWorldType(int value) {
        
        worldType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * OKCAGDNDEJN
       * </pre>
       *
       * <code>uint32 world_type = 1870;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorldType() {
        
        worldType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerEnterSceneNotify)
    }

    // @@protoc_insertion_point(class_scope:PlayerEnterSceneNotify)
    private static final raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify();
    }

    public static raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerEnterSceneNotify>
        PARSER = new com.google.protobuf.AbstractParser<PlayerEnterSceneNotify>() {
      @java.lang.Override
      public PlayerEnterSceneNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerEnterSceneNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerEnterSceneNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerEnterSceneNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.PlayerEnterSceneNotifyOuterClass.PlayerEnterSceneNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerEnterSceneNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerEnterSceneNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034PlayerEnterSceneNotify.proto\032\014Vector.p" +
      "roto\032\022MapLayerInfo.proto\"\263\004\n\026PlayerEnter" +
      "SceneNotify\022\022\n\nis_skip_ui\030\001 \001(\010\022\031\n\010prev_" +
      "pos\030\002 \001(\0132\007.Vector\022\023\n\013world_level\030\003 \001(\r\022" +
      "\022\n\ntarget_uid\030\004 \001(\r\022\030\n\020scene_begin_time\030" +
      "\005 \001(\004\022\031\n\021scene_tag_id_list\030\006 \003(\r\022\031\n\021ente" +
      "r_scene_token\030\007 \001(\r\022\022\n\ndungeon_id\030\013 \001(\r\022" +
      "\025\n\rprev_scene_id\030\014 \001(\r\022\024\n\003pos\030\r \001(\0132\007.Ve" +
      "ctor\022\020\n\010scene_id\030\016 \001(\r\022\014\n\004type\030\017 \001(\r\022\024\n\013" +
      "ALJNJKPMOPB\030\322\002 \001(\r\022\024\n\013EKIBACGBHCJ\030\346\002 \001(\r" +
      "\022\024\n\013KDHNDLANKNI\030\320\003 \001(\r\022&\n\016map_layer_info" +
      "\030\344\005 \001(\0132\r.MapLayerInfo\022\035\n\013KMDLMKGJIHH\030\210\006" +
      " \001(\0132\007.Vector\022#\n\032is_first_login_enter_sc" +
      "ene\030\260\006 \001(\010\022\025\n\014enter_reason\030\374\010 \001(\r\022\032\n\021sce" +
      "ne_transaction\030\324\013 \001(\t\022\032\n\021create_player_u" +
      "id\030\240\r \001(\r\022\023\n\nworld_type\030\316\016 \001(\rB\033\n\031raiden" +
      "game.cache.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          raidengame.cache.protobuf.VectorOuterClass.getDescriptor(),
          raidengame.cache.protobuf.MapLayerInfoOuterClass.getDescriptor(),
        });
    internal_static_PlayerEnterSceneNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerEnterSceneNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerEnterSceneNotify_descriptor,
        new java.lang.String[] { "IsSkipUi", "PrevPos", "WorldLevel", "TargetUid", "SceneBeginTime", "SceneTagIdList", "EnterSceneToken", "DungeonId", "PrevSceneId", "Pos", "SceneId", "Type", "ALJNJKPMOPB", "EKIBACGBHCJ", "KDHNDLANKNI", "MapLayerInfo", "KMDLMKGJIHH", "IsFirstLoginEnterScene", "EnterReason", "SceneTransaction", "CreatePlayerUid", "WorldType", });
    raidengame.cache.protobuf.VectorOuterClass.getDescriptor();
    raidengame.cache.protobuf.MapLayerInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
