// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QueryCurrRegionHttpRsp.proto

package raidengame.cache.protobuf;

public final class QueryCurrRegionHttpRspOuterClass {
  private QueryCurrRegionHttpRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryCurrRegionHttpRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QueryCurrRegionHttpRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return Whether the regionInfo field is set.
     */
    boolean hasRegionInfo();
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return The regionInfo.
     */
    raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo getRegionInfo();
    /**
     * <code>.RegionInfo region_info = 3;</code>
     */
    raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder();

    /**
     * <code>bytes client_secret_key = 11;</code>
     * @return The clientSecretKey.
     */
    com.google.protobuf.ByteString getClientSecretKey();

    /**
     * <code>bytes region_custom_config_encrypted = 12;</code>
     * @return The regionCustomConfigEncrypted.
     */
    com.google.protobuf.ByteString getRegionCustomConfigEncrypted();

    /**
     * <code>bytes client_region_custom_config_encrypted = 13;</code>
     * @return The clientRegionCustomConfigEncrypted.
     */
    com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted();

    /**
     * <code>string connect_gate_ticket = 14;</code>
     * @return The connectGateTicket.
     */
    java.lang.String getConnectGateTicket();
    /**
     * <code>string connect_gate_ticket = 14;</code>
     * @return The bytes for connectGateTicket.
     */
    com.google.protobuf.ByteString
        getConnectGateTicketBytes();
  }
  /**
   * Protobuf type {@code QueryCurrRegionHttpRsp}
   */
  public static final class QueryCurrRegionHttpRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QueryCurrRegionHttpRsp)
      QueryCurrRegionHttpRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCurrRegionHttpRsp.newBuilder() to construct.
    private QueryCurrRegionHttpRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCurrRegionHttpRsp() {
      msg_ = "";
      clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
      regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      connectGateTicket_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCurrRegionHttpRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryCurrRegionHttpRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              retcode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder subBuilder = null;
              if (regionInfo_ != null) {
                subBuilder = regionInfo_.toBuilder();
              }
              regionInfo_ = input.readMessage(raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(regionInfo_);
                regionInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 90: {

              clientSecretKey_ = input.readBytes();
              break;
            }
            case 98: {

              regionCustomConfigEncrypted_ = input.readBytes();
              break;
            }
            case 106: {

              clientRegionCustomConfigEncrypted_ = input.readBytes();
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              connectGateTicket_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.class, raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.Builder.class);
    }

    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retcode_;
    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    @java.lang.Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_INFO_FIELD_NUMBER = 3;
    private raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo regionInfo_;
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return Whether the regionInfo field is set.
     */
    @java.lang.Override
    public boolean hasRegionInfo() {
      return regionInfo_ != null;
    }
    /**
     * <code>.RegionInfo region_info = 3;</code>
     * @return The regionInfo.
     */
    @java.lang.Override
    public raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo getRegionInfo() {
      return regionInfo_ == null ? raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
    }
    /**
     * <code>.RegionInfo region_info = 3;</code>
     */
    @java.lang.Override
    public raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder() {
      return getRegionInfo();
    }

    public static final int CLIENT_SECRET_KEY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString clientSecretKey_;
    /**
     * <code>bytes client_secret_key = 11;</code>
     * @return The clientSecretKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientSecretKey() {
      return clientSecretKey_;
    }

    public static final int REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString regionCustomConfigEncrypted_;
    /**
     * <code>bytes region_custom_config_encrypted = 12;</code>
     * @return The regionCustomConfigEncrypted.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRegionCustomConfigEncrypted() {
      return regionCustomConfigEncrypted_;
    }

    public static final int CLIENT_REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString clientRegionCustomConfigEncrypted_;
    /**
     * <code>bytes client_region_custom_config_encrypted = 13;</code>
     * @return The clientRegionCustomConfigEncrypted.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted() {
      return clientRegionCustomConfigEncrypted_;
    }

    public static final int CONNECT_GATE_TICKET_FIELD_NUMBER = 14;
    private volatile java.lang.Object connectGateTicket_;
    /**
     * <code>string connect_gate_ticket = 14;</code>
     * @return The connectGateTicket.
     */
    @java.lang.Override
    public java.lang.String getConnectGateTicket() {
      java.lang.Object ref = connectGateTicket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectGateTicket_ = s;
        return s;
      }
    }
    /**
     * <code>string connect_gate_ticket = 14;</code>
     * @return The bytes for connectGateTicket.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnectGateTicketBytes() {
      java.lang.Object ref = connectGateTicket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectGateTicket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (retcode_ != 0) {
        output.writeInt32(1, retcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (regionInfo_ != null) {
        output.writeMessage(3, getRegionInfo());
      }
      if (!clientSecretKey_.isEmpty()) {
        output.writeBytes(11, clientSecretKey_);
      }
      if (!regionCustomConfigEncrypted_.isEmpty()) {
        output.writeBytes(12, regionCustomConfigEncrypted_);
      }
      if (!clientRegionCustomConfigEncrypted_.isEmpty()) {
        output.writeBytes(13, clientRegionCustomConfigEncrypted_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectGateTicket_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, connectGateTicket_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (regionInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRegionInfo());
      }
      if (!clientSecretKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, clientSecretKey_);
      }
      if (!regionCustomConfigEncrypted_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, regionCustomConfigEncrypted_);
      }
      if (!clientRegionCustomConfigEncrypted_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, clientRegionCustomConfigEncrypted_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectGateTicket_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, connectGateTicket_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp other = (raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp) obj;

      if (getRetcode()
          != other.getRetcode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (hasRegionInfo() != other.hasRegionInfo()) return false;
      if (hasRegionInfo()) {
        if (!getRegionInfo()
            .equals(other.getRegionInfo())) return false;
      }
      if (!getClientSecretKey()
          .equals(other.getClientSecretKey())) return false;
      if (!getRegionCustomConfigEncrypted()
          .equals(other.getRegionCustomConfigEncrypted())) return false;
      if (!getClientRegionCustomConfigEncrypted()
          .equals(other.getClientRegionCustomConfigEncrypted())) return false;
      if (!getConnectGateTicket()
          .equals(other.getConnectGateTicket())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasRegionInfo()) {
        hash = (37 * hash) + REGION_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getRegionInfo().hashCode();
      }
      hash = (37 * hash) + CLIENT_SECRET_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getClientSecretKey().hashCode();
      hash = (37 * hash) + REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getRegionCustomConfigEncrypted().hashCode();
      hash = (37 * hash) + CLIENT_REGION_CUSTOM_CONFIG_ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getClientRegionCustomConfigEncrypted().hashCode();
      hash = (37 * hash) + CONNECT_GATE_TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getConnectGateTicket().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QueryCurrRegionHttpRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QueryCurrRegionHttpRsp)
        raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.class, raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retcode_ = 0;

        msg_ = "";

        if (regionInfoBuilder_ == null) {
          regionInfo_ = null;
        } else {
          regionInfo_ = null;
          regionInfoBuilder_ = null;
        }
        clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;

        regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;

        clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;

        connectGateTicket_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.internal_static_QueryCurrRegionHttpRsp_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp getDefaultInstanceForType() {
        return raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp build() {
        raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp buildPartial() {
        raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp result = new raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp(this);
        result.retcode_ = retcode_;
        result.msg_ = msg_;
        if (regionInfoBuilder_ == null) {
          result.regionInfo_ = regionInfo_;
        } else {
          result.regionInfo_ = regionInfoBuilder_.build();
        }
        result.clientSecretKey_ = clientSecretKey_;
        result.regionCustomConfigEncrypted_ = regionCustomConfigEncrypted_;
        result.clientRegionCustomConfigEncrypted_ = clientRegionCustomConfigEncrypted_;
        result.connectGateTicket_ = connectGateTicket_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp) {
          return mergeFrom((raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp other) {
        if (other == raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp.getDefaultInstance()) return this;
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasRegionInfo()) {
          mergeRegionInfo(other.getRegionInfo());
        }
        if (other.getClientSecretKey() != com.google.protobuf.ByteString.EMPTY) {
          setClientSecretKey(other.getClientSecretKey());
        }
        if (other.getRegionCustomConfigEncrypted() != com.google.protobuf.ByteString.EMPTY) {
          setRegionCustomConfigEncrypted(other.getRegionCustomConfigEncrypted());
        }
        if (other.getClientRegionCustomConfigEncrypted() != com.google.protobuf.ByteString.EMPTY) {
          setClientRegionCustomConfigEncrypted(other.getClientRegionCustomConfigEncrypted());
        }
        if (!other.getConnectGateTicket().isEmpty()) {
          connectGateTicket_ = other.connectGateTicket_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int retcode_ ;
      /**
       * <code>int32 retcode = 1;</code>
       * @return The retcode.
       */
      @java.lang.Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        
        retcode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo regionInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder> regionInfoBuilder_;
      /**
       * <code>.RegionInfo region_info = 3;</code>
       * @return Whether the regionInfo field is set.
       */
      public boolean hasRegionInfo() {
        return regionInfoBuilder_ != null || regionInfo_ != null;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       * @return The regionInfo.
       */
      public raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo getRegionInfo() {
        if (regionInfoBuilder_ == null) {
          return regionInfo_ == null ? raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
        } else {
          return regionInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder setRegionInfo(raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo value) {
        if (regionInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          regionInfo_ = value;
          onChanged();
        } else {
          regionInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder setRegionInfo(
          raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder builderForValue) {
        if (regionInfoBuilder_ == null) {
          regionInfo_ = builderForValue.build();
          onChanged();
        } else {
          regionInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder mergeRegionInfo(raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo value) {
        if (regionInfoBuilder_ == null) {
          if (regionInfo_ != null) {
            regionInfo_ =
              raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.newBuilder(regionInfo_).mergeFrom(value).buildPartial();
          } else {
            regionInfo_ = value;
          }
          onChanged();
        } else {
          regionInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public Builder clearRegionInfo() {
        if (regionInfoBuilder_ == null) {
          regionInfo_ = null;
          onChanged();
        } else {
          regionInfo_ = null;
          regionInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder getRegionInfoBuilder() {
        
        onChanged();
        return getRegionInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      public raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder getRegionInfoOrBuilder() {
        if (regionInfoBuilder_ != null) {
          return regionInfoBuilder_.getMessageOrBuilder();
        } else {
          return regionInfo_ == null ?
              raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.getDefaultInstance() : regionInfo_;
        }
      }
      /**
       * <code>.RegionInfo region_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder> 
          getRegionInfoFieldBuilder() {
        if (regionInfoBuilder_ == null) {
          regionInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfo.Builder, raidengame.cache.protobuf.RegionInfoOuterClass.RegionInfoOrBuilder>(
                  getRegionInfo(),
                  getParentForChildren(),
                  isClean());
          regionInfo_ = null;
        }
        return regionInfoBuilder_;
      }

      private com.google.protobuf.ByteString clientSecretKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @return The clientSecretKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientSecretKey() {
        return clientSecretKey_;
      }
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @param value The clientSecretKey to set.
       * @return This builder for chaining.
       */
      public Builder setClientSecretKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSecretKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes client_secret_key = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientSecretKey() {
        
        clientSecretKey_ = getDefaultInstance().getClientSecretKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString regionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @return The regionCustomConfigEncrypted.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRegionCustomConfigEncrypted() {
        return regionCustomConfigEncrypted_;
      }
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @param value The regionCustomConfigEncrypted to set.
       * @return This builder for chaining.
       */
      public Builder setRegionCustomConfigEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        regionCustomConfigEncrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes region_custom_config_encrypted = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegionCustomConfigEncrypted() {
        
        regionCustomConfigEncrypted_ = getDefaultInstance().getRegionCustomConfigEncrypted();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString clientRegionCustomConfigEncrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @return The clientRegionCustomConfigEncrypted.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientRegionCustomConfigEncrypted() {
        return clientRegionCustomConfigEncrypted_;
      }
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @param value The clientRegionCustomConfigEncrypted to set.
       * @return This builder for chaining.
       */
      public Builder setClientRegionCustomConfigEncrypted(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientRegionCustomConfigEncrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes client_region_custom_config_encrypted = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientRegionCustomConfigEncrypted() {
        
        clientRegionCustomConfigEncrypted_ = getDefaultInstance().getClientRegionCustomConfigEncrypted();
        onChanged();
        return this;
      }

      private java.lang.Object connectGateTicket_ = "";
      /**
       * <code>string connect_gate_ticket = 14;</code>
       * @return The connectGateTicket.
       */
      public java.lang.String getConnectGateTicket() {
        java.lang.Object ref = connectGateTicket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connectGateTicket_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connect_gate_ticket = 14;</code>
       * @return The bytes for connectGateTicket.
       */
      public com.google.protobuf.ByteString
          getConnectGateTicketBytes() {
        java.lang.Object ref = connectGateTicket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connectGateTicket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connect_gate_ticket = 14;</code>
       * @param value The connectGateTicket to set.
       * @return This builder for chaining.
       */
      public Builder setConnectGateTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connectGateTicket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connect_gate_ticket = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectGateTicket() {
        
        connectGateTicket_ = getDefaultInstance().getConnectGateTicket();
        onChanged();
        return this;
      }
      /**
       * <code>string connect_gate_ticket = 14;</code>
       * @param value The bytes for connectGateTicket to set.
       * @return This builder for chaining.
       */
      public Builder setConnectGateTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connectGateTicket_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QueryCurrRegionHttpRsp)
    }

    // @@protoc_insertion_point(class_scope:QueryCurrRegionHttpRsp)
    private static final raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp();
    }

    public static raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCurrRegionHttpRsp>
        PARSER = new com.google.protobuf.AbstractParser<QueryCurrRegionHttpRsp>() {
      @java.lang.Override
      public QueryCurrRegionHttpRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryCurrRegionHttpRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryCurrRegionHttpRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryCurrRegionHttpRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.QueryCurrRegionHttpRspOuterClass.QueryCurrRegionHttpRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueryCurrRegionHttpRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034QueryCurrRegionHttpRsp.proto\032\020RegionIn" +
      "fo.proto\"\347\001\n\026QueryCurrRegionHttpRsp\022\017\n\007r" +
      "etcode\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022 \n\013region_info" +
      "\030\003 \001(\0132\013.RegionInfo\022\031\n\021client_secret_key" +
      "\030\013 \001(\014\022&\n\036region_custom_config_encrypted" +
      "\030\014 \001(\014\022-\n%client_region_custom_config_en" +
      "crypted\030\r \001(\014\022\033\n\023connect_gate_ticket\030\016 \001" +
      "(\tB\033\n\031raidengame.cache.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          raidengame.cache.protobuf.RegionInfoOuterClass.getDescriptor(),
        });
    internal_static_QueryCurrRegionHttpRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QueryCurrRegionHttpRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueryCurrRegionHttpRsp_descriptor,
        new java.lang.String[] { "Retcode", "Msg", "RegionInfo", "ClientSecretKey", "RegionCustomConfigEncrypted", "ClientRegionCustomConfigEncrypted", "ConnectGateTicket", });
    raidengame.cache.protobuf.RegionInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
