// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrackingIOInfo.proto

package raidengame.cache.protobuf;

public final class TrackingIOInfoOuterClass {
  private TrackingIOInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrackingIOInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TrackingIOInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string EHMNEFANLGI = 1;</code>
     * @return The eHMNEFANLGI.
     */
    java.lang.String getEHMNEFANLGI();
    /**
     * <code>string EHMNEFANLGI = 1;</code>
     * @return The bytes for eHMNEFANLGI.
     */
    com.google.protobuf.ByteString
        getEHMNEFANLGIBytes();

    /**
     * <code>string IFNECHPPKKE = 2;</code>
     * @return The iFNECHPPKKE.
     */
    java.lang.String getIFNECHPPKKE();
    /**
     * <code>string IFNECHPPKKE = 2;</code>
     * @return The bytes for iFNECHPPKKE.
     */
    com.google.protobuf.ByteString
        getIFNECHPPKKEBytes();

    /**
     * <code>string HNFGIHDNGCB = 3;</code>
     * @return The hNFGIHDNGCB.
     */
    java.lang.String getHNFGIHDNGCB();
    /**
     * <code>string HNFGIHDNGCB = 3;</code>
     * @return The bytes for hNFGIHDNGCB.
     */
    com.google.protobuf.ByteString
        getHNFGIHDNGCBBytes();

    /**
     * <code>string HBBLMFKFPKF = 4;</code>
     * @return The hBBLMFKFPKF.
     */
    java.lang.String getHBBLMFKFPKF();
    /**
     * <code>string HBBLMFKFPKF = 4;</code>
     * @return The bytes for hBBLMFKFPKF.
     */
    com.google.protobuf.ByteString
        getHBBLMFKFPKFBytes();

    /**
     * <code>string GEJMEOLDGIO = 6;</code>
     * @return The gEJMEOLDGIO.
     */
    java.lang.String getGEJMEOLDGIO();
    /**
     * <code>string GEJMEOLDGIO = 6;</code>
     * @return The bytes for gEJMEOLDGIO.
     */
    com.google.protobuf.ByteString
        getGEJMEOLDGIOBytes();

    /**
     * <code>string OFGKPPHKBCL = 14;</code>
     * @return The oFGKPPHKBCL.
     */
    java.lang.String getOFGKPPHKBCL();
    /**
     * <code>string OFGKPPHKBCL = 14;</code>
     * @return The bytes for oFGKPPHKBCL.
     */
    com.google.protobuf.ByteString
        getOFGKPPHKBCLBytes();

    /**
     * <code>string NJPDGKMNOHN = 15;</code>
     * @return The nJPDGKMNOHN.
     */
    java.lang.String getNJPDGKMNOHN();
    /**
     * <code>string NJPDGKMNOHN = 15;</code>
     * @return The bytes for nJPDGKMNOHN.
     */
    com.google.protobuf.ByteString
        getNJPDGKMNOHNBytes();
  }
  /**
   * Protobuf type {@code TrackingIOInfo}
   */
  public static final class TrackingIOInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TrackingIOInfo)
      TrackingIOInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrackingIOInfo.newBuilder() to construct.
    private TrackingIOInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackingIOInfo() {
      eHMNEFANLGI_ = "";
      iFNECHPPKKE_ = "";
      hNFGIHDNGCB_ = "";
      hBBLMFKFPKF_ = "";
      gEJMEOLDGIO_ = "";
      oFGKPPHKBCL_ = "";
      nJPDGKMNOHN_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TrackingIOInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrackingIOInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              eHMNEFANLGI_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              iFNECHPPKKE_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              hNFGIHDNGCB_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              hBBLMFKFPKF_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              gEJMEOLDGIO_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              oFGKPPHKBCL_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              nJPDGKMNOHN_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return raidengame.cache.protobuf.TrackingIOInfoOuterClass.internal_static_TrackingIOInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return raidengame.cache.protobuf.TrackingIOInfoOuterClass.internal_static_TrackingIOInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.class, raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.Builder.class);
    }

    public static final int EHMNEFANLGI_FIELD_NUMBER = 1;
    private volatile java.lang.Object eHMNEFANLGI_;
    /**
     * <code>string EHMNEFANLGI = 1;</code>
     * @return The eHMNEFANLGI.
     */
    @java.lang.Override
    public java.lang.String getEHMNEFANLGI() {
      java.lang.Object ref = eHMNEFANLGI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eHMNEFANLGI_ = s;
        return s;
      }
    }
    /**
     * <code>string EHMNEFANLGI = 1;</code>
     * @return The bytes for eHMNEFANLGI.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEHMNEFANLGIBytes() {
      java.lang.Object ref = eHMNEFANLGI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eHMNEFANLGI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IFNECHPPKKE_FIELD_NUMBER = 2;
    private volatile java.lang.Object iFNECHPPKKE_;
    /**
     * <code>string IFNECHPPKKE = 2;</code>
     * @return The iFNECHPPKKE.
     */
    @java.lang.Override
    public java.lang.String getIFNECHPPKKE() {
      java.lang.Object ref = iFNECHPPKKE_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iFNECHPPKKE_ = s;
        return s;
      }
    }
    /**
     * <code>string IFNECHPPKKE = 2;</code>
     * @return The bytes for iFNECHPPKKE.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIFNECHPPKKEBytes() {
      java.lang.Object ref = iFNECHPPKKE_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iFNECHPPKKE_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HNFGIHDNGCB_FIELD_NUMBER = 3;
    private volatile java.lang.Object hNFGIHDNGCB_;
    /**
     * <code>string HNFGIHDNGCB = 3;</code>
     * @return The hNFGIHDNGCB.
     */
    @java.lang.Override
    public java.lang.String getHNFGIHDNGCB() {
      java.lang.Object ref = hNFGIHDNGCB_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hNFGIHDNGCB_ = s;
        return s;
      }
    }
    /**
     * <code>string HNFGIHDNGCB = 3;</code>
     * @return The bytes for hNFGIHDNGCB.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHNFGIHDNGCBBytes() {
      java.lang.Object ref = hNFGIHDNGCB_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hNFGIHDNGCB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HBBLMFKFPKF_FIELD_NUMBER = 4;
    private volatile java.lang.Object hBBLMFKFPKF_;
    /**
     * <code>string HBBLMFKFPKF = 4;</code>
     * @return The hBBLMFKFPKF.
     */
    @java.lang.Override
    public java.lang.String getHBBLMFKFPKF() {
      java.lang.Object ref = hBBLMFKFPKF_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hBBLMFKFPKF_ = s;
        return s;
      }
    }
    /**
     * <code>string HBBLMFKFPKF = 4;</code>
     * @return The bytes for hBBLMFKFPKF.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHBBLMFKFPKFBytes() {
      java.lang.Object ref = hBBLMFKFPKF_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hBBLMFKFPKF_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEJMEOLDGIO_FIELD_NUMBER = 6;
    private volatile java.lang.Object gEJMEOLDGIO_;
    /**
     * <code>string GEJMEOLDGIO = 6;</code>
     * @return The gEJMEOLDGIO.
     */
    @java.lang.Override
    public java.lang.String getGEJMEOLDGIO() {
      java.lang.Object ref = gEJMEOLDGIO_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gEJMEOLDGIO_ = s;
        return s;
      }
    }
    /**
     * <code>string GEJMEOLDGIO = 6;</code>
     * @return The bytes for gEJMEOLDGIO.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGEJMEOLDGIOBytes() {
      java.lang.Object ref = gEJMEOLDGIO_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gEJMEOLDGIO_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFGKPPHKBCL_FIELD_NUMBER = 14;
    private volatile java.lang.Object oFGKPPHKBCL_;
    /**
     * <code>string OFGKPPHKBCL = 14;</code>
     * @return The oFGKPPHKBCL.
     */
    @java.lang.Override
    public java.lang.String getOFGKPPHKBCL() {
      java.lang.Object ref = oFGKPPHKBCL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oFGKPPHKBCL_ = s;
        return s;
      }
    }
    /**
     * <code>string OFGKPPHKBCL = 14;</code>
     * @return The bytes for oFGKPPHKBCL.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOFGKPPHKBCLBytes() {
      java.lang.Object ref = oFGKPPHKBCL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oFGKPPHKBCL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NJPDGKMNOHN_FIELD_NUMBER = 15;
    private volatile java.lang.Object nJPDGKMNOHN_;
    /**
     * <code>string NJPDGKMNOHN = 15;</code>
     * @return The nJPDGKMNOHN.
     */
    @java.lang.Override
    public java.lang.String getNJPDGKMNOHN() {
      java.lang.Object ref = nJPDGKMNOHN_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nJPDGKMNOHN_ = s;
        return s;
      }
    }
    /**
     * <code>string NJPDGKMNOHN = 15;</code>
     * @return The bytes for nJPDGKMNOHN.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNJPDGKMNOHNBytes() {
      java.lang.Object ref = nJPDGKMNOHN_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nJPDGKMNOHN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eHMNEFANLGI_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eHMNEFANLGI_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iFNECHPPKKE_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iFNECHPPKKE_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hNFGIHDNGCB_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hNFGIHDNGCB_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hBBLMFKFPKF_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hBBLMFKFPKF_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gEJMEOLDGIO_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gEJMEOLDGIO_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oFGKPPHKBCL_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, oFGKPPHKBCL_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nJPDGKMNOHN_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, nJPDGKMNOHN_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eHMNEFANLGI_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eHMNEFANLGI_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iFNECHPPKKE_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iFNECHPPKKE_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hNFGIHDNGCB_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hNFGIHDNGCB_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hBBLMFKFPKF_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hBBLMFKFPKF_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gEJMEOLDGIO_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gEJMEOLDGIO_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(oFGKPPHKBCL_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, oFGKPPHKBCL_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nJPDGKMNOHN_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, nJPDGKMNOHN_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo)) {
        return super.equals(obj);
      }
      raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo other = (raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo) obj;

      if (!getEHMNEFANLGI()
          .equals(other.getEHMNEFANLGI())) return false;
      if (!getIFNECHPPKKE()
          .equals(other.getIFNECHPPKKE())) return false;
      if (!getHNFGIHDNGCB()
          .equals(other.getHNFGIHDNGCB())) return false;
      if (!getHBBLMFKFPKF()
          .equals(other.getHBBLMFKFPKF())) return false;
      if (!getGEJMEOLDGIO()
          .equals(other.getGEJMEOLDGIO())) return false;
      if (!getOFGKPPHKBCL()
          .equals(other.getOFGKPPHKBCL())) return false;
      if (!getNJPDGKMNOHN()
          .equals(other.getNJPDGKMNOHN())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EHMNEFANLGI_FIELD_NUMBER;
      hash = (53 * hash) + getEHMNEFANLGI().hashCode();
      hash = (37 * hash) + IFNECHPPKKE_FIELD_NUMBER;
      hash = (53 * hash) + getIFNECHPPKKE().hashCode();
      hash = (37 * hash) + HNFGIHDNGCB_FIELD_NUMBER;
      hash = (53 * hash) + getHNFGIHDNGCB().hashCode();
      hash = (37 * hash) + HBBLMFKFPKF_FIELD_NUMBER;
      hash = (53 * hash) + getHBBLMFKFPKF().hashCode();
      hash = (37 * hash) + GEJMEOLDGIO_FIELD_NUMBER;
      hash = (53 * hash) + getGEJMEOLDGIO().hashCode();
      hash = (37 * hash) + OFGKPPHKBCL_FIELD_NUMBER;
      hash = (53 * hash) + getOFGKPPHKBCL().hashCode();
      hash = (37 * hash) + NJPDGKMNOHN_FIELD_NUMBER;
      hash = (53 * hash) + getNJPDGKMNOHN().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TrackingIOInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TrackingIOInfo)
        raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return raidengame.cache.protobuf.TrackingIOInfoOuterClass.internal_static_TrackingIOInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return raidengame.cache.protobuf.TrackingIOInfoOuterClass.internal_static_TrackingIOInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.class, raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.Builder.class);
      }

      // Construct using raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eHMNEFANLGI_ = "";

        iFNECHPPKKE_ = "";

        hNFGIHDNGCB_ = "";

        hBBLMFKFPKF_ = "";

        gEJMEOLDGIO_ = "";

        oFGKPPHKBCL_ = "";

        nJPDGKMNOHN_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return raidengame.cache.protobuf.TrackingIOInfoOuterClass.internal_static_TrackingIOInfo_descriptor;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo getDefaultInstanceForType() {
        return raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.getDefaultInstance();
      }

      @java.lang.Override
      public raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo build() {
        raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo buildPartial() {
        raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo result = new raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo(this);
        result.eHMNEFANLGI_ = eHMNEFANLGI_;
        result.iFNECHPPKKE_ = iFNECHPPKKE_;
        result.hNFGIHDNGCB_ = hNFGIHDNGCB_;
        result.hBBLMFKFPKF_ = hBBLMFKFPKF_;
        result.gEJMEOLDGIO_ = gEJMEOLDGIO_;
        result.oFGKPPHKBCL_ = oFGKPPHKBCL_;
        result.nJPDGKMNOHN_ = nJPDGKMNOHN_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo) {
          return mergeFrom((raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo other) {
        if (other == raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo.getDefaultInstance()) return this;
        if (!other.getEHMNEFANLGI().isEmpty()) {
          eHMNEFANLGI_ = other.eHMNEFANLGI_;
          onChanged();
        }
        if (!other.getIFNECHPPKKE().isEmpty()) {
          iFNECHPPKKE_ = other.iFNECHPPKKE_;
          onChanged();
        }
        if (!other.getHNFGIHDNGCB().isEmpty()) {
          hNFGIHDNGCB_ = other.hNFGIHDNGCB_;
          onChanged();
        }
        if (!other.getHBBLMFKFPKF().isEmpty()) {
          hBBLMFKFPKF_ = other.hBBLMFKFPKF_;
          onChanged();
        }
        if (!other.getGEJMEOLDGIO().isEmpty()) {
          gEJMEOLDGIO_ = other.gEJMEOLDGIO_;
          onChanged();
        }
        if (!other.getOFGKPPHKBCL().isEmpty()) {
          oFGKPPHKBCL_ = other.oFGKPPHKBCL_;
          onChanged();
        }
        if (!other.getNJPDGKMNOHN().isEmpty()) {
          nJPDGKMNOHN_ = other.nJPDGKMNOHN_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object eHMNEFANLGI_ = "";
      /**
       * <code>string EHMNEFANLGI = 1;</code>
       * @return The eHMNEFANLGI.
       */
      public java.lang.String getEHMNEFANLGI() {
        java.lang.Object ref = eHMNEFANLGI_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eHMNEFANLGI_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EHMNEFANLGI = 1;</code>
       * @return The bytes for eHMNEFANLGI.
       */
      public com.google.protobuf.ByteString
          getEHMNEFANLGIBytes() {
        java.lang.Object ref = eHMNEFANLGI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eHMNEFANLGI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EHMNEFANLGI = 1;</code>
       * @param value The eHMNEFANLGI to set.
       * @return This builder for chaining.
       */
      public Builder setEHMNEFANLGI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eHMNEFANLGI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string EHMNEFANLGI = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEHMNEFANLGI() {
        
        eHMNEFANLGI_ = getDefaultInstance().getEHMNEFANLGI();
        onChanged();
        return this;
      }
      /**
       * <code>string EHMNEFANLGI = 1;</code>
       * @param value The bytes for eHMNEFANLGI to set.
       * @return This builder for chaining.
       */
      public Builder setEHMNEFANLGIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eHMNEFANLGI_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iFNECHPPKKE_ = "";
      /**
       * <code>string IFNECHPPKKE = 2;</code>
       * @return The iFNECHPPKKE.
       */
      public java.lang.String getIFNECHPPKKE() {
        java.lang.Object ref = iFNECHPPKKE_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iFNECHPPKKE_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string IFNECHPPKKE = 2;</code>
       * @return The bytes for iFNECHPPKKE.
       */
      public com.google.protobuf.ByteString
          getIFNECHPPKKEBytes() {
        java.lang.Object ref = iFNECHPPKKE_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iFNECHPPKKE_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IFNECHPPKKE = 2;</code>
       * @param value The iFNECHPPKKE to set.
       * @return This builder for chaining.
       */
      public Builder setIFNECHPPKKE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iFNECHPPKKE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IFNECHPPKKE = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIFNECHPPKKE() {
        
        iFNECHPPKKE_ = getDefaultInstance().getIFNECHPPKKE();
        onChanged();
        return this;
      }
      /**
       * <code>string IFNECHPPKKE = 2;</code>
       * @param value The bytes for iFNECHPPKKE to set.
       * @return This builder for chaining.
       */
      public Builder setIFNECHPPKKEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iFNECHPPKKE_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hNFGIHDNGCB_ = "";
      /**
       * <code>string HNFGIHDNGCB = 3;</code>
       * @return The hNFGIHDNGCB.
       */
      public java.lang.String getHNFGIHDNGCB() {
        java.lang.Object ref = hNFGIHDNGCB_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hNFGIHDNGCB_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string HNFGIHDNGCB = 3;</code>
       * @return The bytes for hNFGIHDNGCB.
       */
      public com.google.protobuf.ByteString
          getHNFGIHDNGCBBytes() {
        java.lang.Object ref = hNFGIHDNGCB_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hNFGIHDNGCB_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string HNFGIHDNGCB = 3;</code>
       * @param value The hNFGIHDNGCB to set.
       * @return This builder for chaining.
       */
      public Builder setHNFGIHDNGCB(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hNFGIHDNGCB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string HNFGIHDNGCB = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHNFGIHDNGCB() {
        
        hNFGIHDNGCB_ = getDefaultInstance().getHNFGIHDNGCB();
        onChanged();
        return this;
      }
      /**
       * <code>string HNFGIHDNGCB = 3;</code>
       * @param value The bytes for hNFGIHDNGCB to set.
       * @return This builder for chaining.
       */
      public Builder setHNFGIHDNGCBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hNFGIHDNGCB_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hBBLMFKFPKF_ = "";
      /**
       * <code>string HBBLMFKFPKF = 4;</code>
       * @return The hBBLMFKFPKF.
       */
      public java.lang.String getHBBLMFKFPKF() {
        java.lang.Object ref = hBBLMFKFPKF_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hBBLMFKFPKF_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string HBBLMFKFPKF = 4;</code>
       * @return The bytes for hBBLMFKFPKF.
       */
      public com.google.protobuf.ByteString
          getHBBLMFKFPKFBytes() {
        java.lang.Object ref = hBBLMFKFPKF_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hBBLMFKFPKF_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string HBBLMFKFPKF = 4;</code>
       * @param value The hBBLMFKFPKF to set.
       * @return This builder for chaining.
       */
      public Builder setHBBLMFKFPKF(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hBBLMFKFPKF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string HBBLMFKFPKF = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHBBLMFKFPKF() {
        
        hBBLMFKFPKF_ = getDefaultInstance().getHBBLMFKFPKF();
        onChanged();
        return this;
      }
      /**
       * <code>string HBBLMFKFPKF = 4;</code>
       * @param value The bytes for hBBLMFKFPKF to set.
       * @return This builder for chaining.
       */
      public Builder setHBBLMFKFPKFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hBBLMFKFPKF_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gEJMEOLDGIO_ = "";
      /**
       * <code>string GEJMEOLDGIO = 6;</code>
       * @return The gEJMEOLDGIO.
       */
      public java.lang.String getGEJMEOLDGIO() {
        java.lang.Object ref = gEJMEOLDGIO_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gEJMEOLDGIO_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string GEJMEOLDGIO = 6;</code>
       * @return The bytes for gEJMEOLDGIO.
       */
      public com.google.protobuf.ByteString
          getGEJMEOLDGIOBytes() {
        java.lang.Object ref = gEJMEOLDGIO_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gEJMEOLDGIO_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string GEJMEOLDGIO = 6;</code>
       * @param value The gEJMEOLDGIO to set.
       * @return This builder for chaining.
       */
      public Builder setGEJMEOLDGIO(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gEJMEOLDGIO_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string GEJMEOLDGIO = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGEJMEOLDGIO() {
        
        gEJMEOLDGIO_ = getDefaultInstance().getGEJMEOLDGIO();
        onChanged();
        return this;
      }
      /**
       * <code>string GEJMEOLDGIO = 6;</code>
       * @param value The bytes for gEJMEOLDGIO to set.
       * @return This builder for chaining.
       */
      public Builder setGEJMEOLDGIOBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gEJMEOLDGIO_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object oFGKPPHKBCL_ = "";
      /**
       * <code>string OFGKPPHKBCL = 14;</code>
       * @return The oFGKPPHKBCL.
       */
      public java.lang.String getOFGKPPHKBCL() {
        java.lang.Object ref = oFGKPPHKBCL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oFGKPPHKBCL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string OFGKPPHKBCL = 14;</code>
       * @return The bytes for oFGKPPHKBCL.
       */
      public com.google.protobuf.ByteString
          getOFGKPPHKBCLBytes() {
        java.lang.Object ref = oFGKPPHKBCL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oFGKPPHKBCL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string OFGKPPHKBCL = 14;</code>
       * @param value The oFGKPPHKBCL to set.
       * @return This builder for chaining.
       */
      public Builder setOFGKPPHKBCL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oFGKPPHKBCL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string OFGKPPHKBCL = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearOFGKPPHKBCL() {
        
        oFGKPPHKBCL_ = getDefaultInstance().getOFGKPPHKBCL();
        onChanged();
        return this;
      }
      /**
       * <code>string OFGKPPHKBCL = 14;</code>
       * @param value The bytes for oFGKPPHKBCL to set.
       * @return This builder for chaining.
       */
      public Builder setOFGKPPHKBCLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oFGKPPHKBCL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nJPDGKMNOHN_ = "";
      /**
       * <code>string NJPDGKMNOHN = 15;</code>
       * @return The nJPDGKMNOHN.
       */
      public java.lang.String getNJPDGKMNOHN() {
        java.lang.Object ref = nJPDGKMNOHN_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nJPDGKMNOHN_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string NJPDGKMNOHN = 15;</code>
       * @return The bytes for nJPDGKMNOHN.
       */
      public com.google.protobuf.ByteString
          getNJPDGKMNOHNBytes() {
        java.lang.Object ref = nJPDGKMNOHN_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nJPDGKMNOHN_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string NJPDGKMNOHN = 15;</code>
       * @param value The nJPDGKMNOHN to set.
       * @return This builder for chaining.
       */
      public Builder setNJPDGKMNOHN(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nJPDGKMNOHN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string NJPDGKMNOHN = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearNJPDGKMNOHN() {
        
        nJPDGKMNOHN_ = getDefaultInstance().getNJPDGKMNOHN();
        onChanged();
        return this;
      }
      /**
       * <code>string NJPDGKMNOHN = 15;</code>
       * @param value The bytes for nJPDGKMNOHN to set.
       * @return This builder for chaining.
       */
      public Builder setNJPDGKMNOHNBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nJPDGKMNOHN_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TrackingIOInfo)
    }

    // @@protoc_insertion_point(class_scope:TrackingIOInfo)
    private static final raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo();
    }

    public static raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrackingIOInfo>
        PARSER = new com.google.protobuf.AbstractParser<TrackingIOInfo>() {
      @java.lang.Override
      public TrackingIOInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrackingIOInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrackingIOInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrackingIOInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public raidengame.cache.protobuf.TrackingIOInfoOuterClass.TrackingIOInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrackingIOInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrackingIOInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024TrackingIOInfo.proto\"\243\001\n\016TrackingIOInf" +
      "o\022\023\n\013EHMNEFANLGI\030\001 \001(\t\022\023\n\013IFNECHPPKKE\030\002 " +
      "\001(\t\022\023\n\013HNFGIHDNGCB\030\003 \001(\t\022\023\n\013HBBLMFKFPKF\030" +
      "\004 \001(\t\022\023\n\013GEJMEOLDGIO\030\006 \001(\t\022\023\n\013OFGKPPHKBC" +
      "L\030\016 \001(\t\022\023\n\013NJPDGKMNOHN\030\017 \001(\tB\033\n\031raidenga" +
      "me.cache.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TrackingIOInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TrackingIOInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrackingIOInfo_descriptor,
        new java.lang.String[] { "EHMNEFANLGI", "IFNECHPPKKE", "HNFGIHDNGCB", "HBBLMFKFPKF", "GEJMEOLDGIO", "OFGKPPHKBCL", "NJPDGKMNOHN", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
